### ISSUE TITLE
FlowRouter with custom integrations never track page

### ISSUE THREAD

**Issue by arthuryeti** [okgrow/analytics#100]
Hi guys,

I'm working with FlowRouter and I built my own version of analytics.js with the integrations that I need. (adroll, drip, google analytics, hellobar, olark). It's working well with the 0.4.3 with the timeout hack to initiate, but when I upgrade to the last version. It seems to never trigger the ready event. Do you have any idea?

Thanks

**Comment by benstr** [comment]
@Atu do you have an example app we can use to verify?

**Comment by derouck** [comment]
@Atu I bet you're having the same issue as I was having with some of the packages. Most of these packages want to get the first page when they are loaded. Analytics.js will only load these packages when you do the first call to track a page view. Hence, the ready call is not made as this will only be triggered once initialisation is completed.

I checked the main analytics quickly and I saw that all these packages have this behavior: adroll, drip, hellobar, olark

More information here: https://github.com/okgrow/analytics/issues/108
