### ISSUE TITLE
Not tracking initial page load

### ISSUE THREAD

**Issue by ipa1981** [okgrow/analytics#101]
Hi, I've realized that first page load for some reason is not tracked in Google analytics. The pageview tracked only on route change. Is it something with my configuration or a common issue? I'm using  SSR, maybe this is somehow cause of the problem?

**Comment by benstr** [comment]
@ipa1981 can you provide an example repo demonstrating the issue? Thanks!

**Comment by ipa1981** [comment]
@benstr I've checked it again - and it now works. Maybe something has been updated during that month. Closing issue
