### ISSUE TITLE
Multiple domain tracking GA

### ISSUE THREAD

**Issue by danielparas** [okgrow/analytics#102]
Hi, first of all thanks the great plugin!

Is there a way to setup multiple domain tracking for google analytics using this plugin? [GA docs](https://support.google.com/analytics/answer/1034342) mention modifying the script.

Thanks in advance
Daniel

**Comment by benstr** [comment]
@danielparas since we have not gotten multiple requests for this feature we will likely not develop it. If you have a solution please submit a PR :)
