### ISSUE TITLE
how to define customized user fields?

### ISSUE THREAD

**Issue by zhaoyao91** [okgrow/analytics#104]
you just set email, but we want to set phone and other fields of user. how should we do?

**Comment by rgould** [comment]
I believe that you can specify any property that you want when you call an analytics function. For example:

``` js
analytics.track("Sign up", {
  username: "foo",
  phone: 1234567890,
  email: "foo@example.com"
});
```

I believe it's specific to which analytics tracker you're using (google analytics, mixpanel, etc). I would look at the (analytics.js)[https://segment.com/docs/libraries/analytics.js/] documentation for more info.
