### ISSUE TITLE
Disable In Development?

### ISSUE THREAD

**Issue by joncursi** [okgrow/analytics#105]
Is there an easy way to disable this package from executing in development? Browser reports the error

```
Missing analyticsSettings in Meteor.settings.public
```

but I do not want tracking in dev.

**Comment by rafa-munoz** [comment]
Which version are you using? I'm using `okgrow:analytics@1.0.5` and I don't get such a message.

Edit: OK, now I see it in the console, that's true. You can ignore it I guess!

**Comment by joncursi** [comment]
Haha, I'm in my browser console 24/7 while developing, it's bothering me a bit there!

**Comment by rgould** [comment]
@joncursi We do actually recommend using it in development, just with separate credentials pointing to test analytics accounts. That way your development environment mirrors production more closely.

That said if you still want to disable it, a workaround is to use a blank option in your `settings.json`:

``` json
{
  "public": {
    "analyticsSettings": { }
   }
}
```

Then it will load silently. 

If there's more demand we'll try and come up with a more elegant solution. PRs are always welcome too :)
