### ISSUE TITLE
Meteor 1.3

### ISSUE THREAD

**Issue by mlecoq** [okgrow/analytics#106]
Does anyone know how we have to import analytics from okgrow ? This

```
import { analytics } from 'meteor/okgrow:analytics';
```

does not work and I do not find any example.

I have the following issue in my console

```
TypeError: _okgrowAnalytics.analytics is undefined
```

on

```
analytics.track('my event');
```

Thanks !

**Comment by dearlordylord** [comment]
Analytics seems to be defined globally for me (I use meteor 1.3.\* and latest analytics package)

**Comment by dearlordylord** [comment]
Maybe it isn't initialised due to settings issue? (just a guess) try to print out your Meteor.settings

**Comment by mlecoq** [comment]
Hi @Firfi , 

I don't have any settings issue. Are you able to import analytics with  
 `import { analytics } from 'meteor/okgrow:analytics';`

After I added the code of this pull request : https://github.com/okgrow/analytics/pull/107 
everything worked fine (and still in production)

If you have an example that works (with code that is not in client directory), I'd like to see it

**Comment by dearlordylord** [comment]
I use it inside client dir actually. Didn't tried with imports so most probably it won't work there without your PR.

**Comment by rgould** [comment]
@mlecoq did you get it working with `import` with PR #107 ? When I tried it out, the imported value was always `undefined`, which makes sense as the module itself doesn't export anything. We'll be looking at refactoring it sometime soon.

**Comment by mlecoq** [comment]
@rgould yes I tried it and it works in production

Example of code I use: 

```
import { analytics } from 'meteor/okgrow:analytics';

...
analytics.track('Error on paiement', { error });
```

And this event is displayed in mixpanel.

I thought that It was sufficient to have analytics as global variable. Am I wrong ?

(I trusted this : http://www.meteorpedia.com/read/Packaging_existing_Libraries - An even simpler solution section)

**Comment by rgould** [comment]
@mlecoq Does it work if you leave out the import statement? (it does for me - `analytics` seems to always be available still)

**Comment by mlecoq** [comment]
@rgould you're right, import statement is not required to use analytics.

**Comment by mlecoq** [comment]
@rgould finally, can we let it as it is for the moment ? You said that you'll refactor it soon. I can make an update in order to have an export with a good scope. It's up to you ;)

**Comment by rgould** [comment]
@mlecoq an update would be welcome! It'll probably take us a couple weeks before we have the time to get around to refactoring

**Comment by mlecoq** [comment]
@rgould 

I have tried to export it with ES2015 syntax.

I added 
    api.use('ecmascript');

In package.js 

Then I wanted to export analytics (as written http://guide.meteor.com/writing-atmosphere-packages.html)

It fails in Meteor.startup 
`meteor-analytics.js:156 Uncaught TypeError: Cannot read property 'initialize' of undefined(anonymous function) @ meteor-analytics.js:156maybeReady @ startup_client.js:26loadingCompleted @ startup_client.js:38`

I think that analytics should be used as a npm dependency in the package before going further. Then It could be imported in meteor projects through the npm dependency. 

With your agreement, I can start this migration.

**Comment by cfnelson** [comment]
@mlecoq v2.0.0 is out which supports es6 import/export for 1.3.1+ packages. Let me know if you have any questions of issues. 

The correct way to import the package is:

``` js
import { analytics } from "meteor/okgrow:analytics";
```

See the flow router example for more details on how it all works.
