### ISSUE TITLE
Event and pageView with auto tracking

### ISSUE THREAD

**Issue by tjcampbell** [okgrow/analytics#109]
Hi Guys

Is it intended behaviour that this package logs both a pageView and a custom page view event on every page change with ga, flowrouter and autorun on? If so is there any way to disable one of them?

**Comment by banjerluke** [comment]
I was wondering this too... and I can't figure out why it's happening, not from the source code at least.

This function calls the page tracker for FlowRouter:
https://github.com/okgrow/analytics/blob/master/client/meteor-analytics.js#L127
...but not the event tracker as far as I can tell.

I actually came here to see whether I could disable the auto-tracking feature entirely as I want to customize the behavior. Looks like setting `Meteor.settings.public.analyticsSettings.autorun` to `false` (in settings.json) will do the trick...

**Comment by RodMachado** [comment]
Hey @tjcampbell 

Yes, this behaviour is currently intended. I guess @banjerluke pretty much answered your question there. You could disable `autorun` and specify which events should be tracked manually.

We could discuss if adding an option for tracking only one event vs all events would be a nice improvement for future versions.
