### ISSUE TITLE
Examples No Longer Exist

### ISSUE THREAD

**Issue by paulgrever** [okgrow/analytics#110]
The links in the Example Section, Iron Router: http://okgrow-analytics-iron-router.meteor.com/ and Flow Router: http://okgrow-analytics-flow-router.meteor.com/ no longer work. This is probably since Meteor moved to Galaxy. 

```
Example Iron Router & Flow Router Apps

This repo includes an examples directory containing 2 simple apps using iron router and flow router. These apps can be run from their directory with meteor --settings settings.json. You can also take a look with them on meteor.com at these links:

Iron Router: http://okgrow-analytics-iron-router.meteor.com/

Flow Router: http://okgrow-analytics-flow-router.meteor.com/
```

**Comment by rgould** [comment]
This was "fixed" by PR #112. For now we're removing them until we have more time to set them up again.
