### ISSUE TITLE
Initial page view not tracked

### ISSUE THREAD

**Issue by dnish** [okgrow/analytics#114]
If I visit my site "www.myapp.com", Google Analytics doesn't show any user online. If I change the route from "/" to "/about", the visit is logged and I can see 1 user online. I'm using FlowRouter + React + Meteor 1.3. Any idea why the first page view isn't tracked? The issue doesn't depend on the route, so if I start on "/about", the visit is also not tracked. Only route changes are tracked.

**Comment by dnish** [comment]
Temp workaround:

```
Meteor.startup(function() {

    //Temp fix because first visit isn't tracked...
    analytics.page(FlowRouter.current().path);
});
```

**Comment by matthlavacka** [comment]
I noticed the same thing with the same setup. Glad I'm not alone.

**Comment by ThomasCin** [comment]
We have the same problem..
