### ISSUE TITLE
implement mixpanel identity first_name, last_name

### ISSUE THREAD

**Issue by markshust** [okgrow/analytics#117]
There is a `mixpanel.people.set` method, which takes custom params, including first_name, last_name, and any other custom fields.

Info per:
https://mixpanel.com/help/reference/creating-a-profile
https://github.com/mixpanel/mixpanel-node#quick-start

`$first_name` and `$last_name` are special fields, but it appears they also allow custom fields to be added. It would be really nice if `identify` allowed these fields to be set, along with any other custom fields.

**Comment by cfnelson** [comment]
@markoshust I took a look at the mixpanel integration for you and as far as I understand this method is already supported by segment.io's analytics.js `.identify()` function, [read instructions here](https://segment.com/docs/integrations/mixpanel/#identify).

If they do not support the functionality you require I would suggest you open an issue on their [mixpanel-integration repo](https://github.com/segment-integrations/analytics.js-integration-mixpanel) as we are using their minified source. 

If I have misunderstood your question please let me know and I will try my best to help.
