### ISSUE TITLE
Push 1.0.7 release to Atmosphere

### ISSUE THREAD

**Issue by skirunman** [okgrow/analytics#118]
Hi @rgould,

Could you please push the 1.0.7 release to Atmosphere. Same issue as https://github.com/okgrow/analytics/issues/116

Thanks!

**Comment by rgould** [comment]
@skirunman Sorry about that! Thought I had, but clearly it either didn't work, or I forgot about it. It's up there now.

**Comment by skirunman** [comment]
Awesome, thanks.
