### ISSUE TITLE
1.0.7 breaks whole app with an ad blocker on

### ISSUE THREAD

**Issue by juho** [okgrow/analytics#120]
Using uBlock Origin:

![screenshot 2016-06-18 17 15 38](https://cloud.githubusercontent.com/assets/399937/16171768/63da8e8e-3578-11e6-910a-3eca6a1530b3.png)

**Comment by BeSports** [comment]
+1

**Comment by Siyfion** [comment]
Yup, only just seem to be getting this problem today after updating, but it's certainly an issue!

**Comment by cfnelson** [comment]
@juho @BeSports @Siyfion I have rolled back the breaking changes of v1.0.7.  [v1.0.8](https://github.com/okgrow/analytics/releases/tag/v1.0.8) is out now and is also up on [Atmosphere](https://atmospherejs.com/okgrow/analytics). Let me know if you have any further issues.

**Comment by juho** [comment]
Thanks!
