### ISSUE TITLE
with google analytics visualisation

### ISSUE THREAD

**Issue by DonFabiolas** [okgrow/analytics#127]
Hello,

on https://analytics.google.com

**this works :**

```
analytics.track("testTrack1");

analytics.track("testTrack2",{ category:"testCategory2" });
```

**this doesn't works, I have got nothing on https://analytics.google.com, any idea ?**

analytics.identify('1e810c197e', {
  name: 'Bill Lumbergh',
  email: 'bill@initech.com'
});

```
analytics.page("home1");

analytics.page("home2",
{
  page:"/yo1",
  name:"s1",
  category:"good1",
  support:"sup1",
  source:"source1",
  title:"tile1",
  location:"loc1",
}
);
```

thank you

**Comment by arrygoo** [comment]
Hey @TroubadourFabiolas,
I just tested the [example app](https://github.com/okgrow/analytics/tree/master/examples/flow-router) and it seems to run fine.

I also pasted your example in the example app and it showed up on https://analytics.google.com .

Do have adblocker on by any chance? If not maybe try you example in the [example app](https://github.com/okgrow/analytics/tree/master/examples/flow-router) to see if it works fine there.

**Comment by DonFabiolas** [comment]
hi @arrygoo thanks for your answer

No, I have not adblocker.

In your example, you use `analytics.on('page'`and I use `analytics.page("home1");` => is it the same ?

Do I need to use "Mixpanel" in settings.json ?

Thank you

**Comment by arrygoo** [comment]
Hey @TroubadourFabiolas, 

I hope I can help you figure this out. Those two are not the same. In the example analytics.on('page', foo) is an event listener, meaning that  "foo" will run everytime a "page" event is emitted. In our example we log it every time 'page' happens.

On the other hand, analytics.page("home1") is the actual trigger of the action, meaning that it will cause a page view to show up in your google analytics.

Is it possible that you're looking at the wrong place in google analytics? Try going to the real-time tab and see if calling the analytics.page("home1") makes it show up there.

Mixpanel doesn't have to be in settings.json, but make sure you're using the correct trackingId. 

If you provide a repo where this is happening we will be able to assist you better.

**Comment by DonFabiolas** [comment]
@arrygoo thank for you answer,

> ... but make sure you're using the correct trackingId
> **=> TrackingId is good because I can see all events analytics.track on https://analytics.google.com**
> 
> Is it possible that you're looking at the wrong place in google analytics? Try going to the real-time tab and see if calling the analytics.page("home1") makes it show up there.
> **=> I looked everywhere to find these "event page" but nothing appears**

For your information : Meteor 1.3.2.4

**Comment by DonFabiolas** [comment]
@arrygoo I just checked on https://analytics.google.com
Yesterday, I didn't see nothing on the real-time tab,
Today, I just saw a page seems tracked,

so, I continue the test and I'll come back tomorrow ;-)

**Comment by DonFabiolas** [comment]
@arrygoo Hello, here you are my results after my latest tests.

with this code 

```
analytics.page("my_page_testing", { //It works on https://analytics.google.com => Reporting => Behaviour => Overview => Page Title
      title: "my_title_testing", //I don't see this information on https://analytics.google.com
      path: "/my/url/testing"//It works on https://analytics.google.com => Reporting => Behaviour => Overview (here page default)
  });
```

Note : On real-time tab, I can see some activity like Url from browser like '/' but we can't see more details of activity.

Thank you @arrygoo for your help.

**Comment by arrygoo** [comment]
@TroubadourFabiolas glad you figured it out!
