### ISSUE TITLE
Do I need to do anything at all for basic tracking?

### ISSUE THREAD

**Issue by t3db0t** [okgrow/analytics#137]
My interpretation of the README suggests that one need not do anything at all after adding the package and adding the `public.analyticsSettings` object in `settings.json`.  I am using Iron-Router and Google Analytics, but I don't see anything coming into GA and I don't see any outgoing network requests to GA.

My `settings.json` looks like:

```
{
    "galaxy.meteor.com": {
        ...
    },
    "public": {
        "analyticsSettings": {
            "Google Analytics" : {"trackingId": "UA-..."}
        }
    }
}
```

Separately: you should add to the readme's section on adblockers that if you see a bunch of package errors in the console, that's why ;)

**Comment by t3db0t** [comment]
Ah ok, my bad, `uBlock Origins` does completely block GA with this package.  Is that to be expected?  This is all in production mode, not development mode.

**Comment by cfnelson** [comment]
@t3db0t Check out the ReadMe's [adblocker](https://github.com/okgrow/analytics#ad-blocker) section. How are you deploying your app ? 

Misunderstood your question. If you have any Ad-blocker on your analytic events will be blocked and the user will not be tracked. This is expected behavior for certain Ad-blockers.

**Comment by t3db0t** [comment]
Yep, that's what I thought, no problem. It just wasn't completely clear in the readme if you meant "it should work even with most adblockers on" or not

**Comment by cfnelson** [comment]
@t3db0t Thanks, hadn't thought about explaining that analytics will not work when adblockers are enabled. Will make a note to add a sentence stating that if you have Adblockers on then analytic events will be blocked.
