### ISSUE TITLE
Google Analytics not working; not sure what to do next

### ISSUE THREAD

**Issue by jimmytidey** [okgrow/analytics#141]
I have installed the package, saw an error about there being no settings.json, added an appropriate settings.json and the error went away. 

In the console I see 

`analytics:integration:google-analytics initialize +0ms`

So everything looks great, but I don't see myself appear in the real time part of GA, it doesn't load a tracking pixel, and the Google Analytics Tag Assistant browser plugin says there is no GA script on the page. 

What should I try next? 

I have a single page app and haven't installed a router at all - could this cause a problem?

**Comment by arrygoo** [comment]
@jimmytidey 
With the current version of Analytics, you need either FlowRouter or IronRouter for analytics page triggers to work. 

@oliverthomasklein has [worked on an update](https://github.com/okgrow/analytics/pull/140) which makes it agnostic to the router that's used.

**Comment by jimmytidey** [comment]
Fantastic, thanks. 

Ok, well I guess for now I'll just add flow router. Hopefully I'll be able to remove it in the future!

Great project!

**Comment by cfnelson** [comment]
@jimmytidey Thanks, the Flow Router example in the repo here may be helpful to you as it demonstrates basic setup/how it works. If you have any other issues or the README is missing anything let us know.
