### ISSUE TITLE
Weird behaviour with 'autorun'":false

### ISSUE THREAD

**Issue by DonFabiolas** [okgrow/analytics#142]
I have 3 events in Google Analytics for the following script. I would like just 1 event in Google Analytics to track properly

In Google Analytics : Real Time => Events => Events (30 last minutes) => event action column

- Viewed innovatorProfileHistory Page
- Viewed public-category Page
- Viewed public-category public-history-profile Page (I just want this line)

**settings.json**

```
{
  "public": {
    "analyticsSettings": {
        "autorun"  : false,
      "Google Analytics" : {
       "trackingId": "XXX"
      }
    }
  }
}
```

**myFile.js**

```
if(typeof analytics !== "undefined")
  {analytics.page("public-category",'public-history-profile');}

```
**How can I get just 1 event to track properly ?**

PS : I made the same post on stackoverflow http://stackoverflow.com/questions/40471015/meteorjs-google-analytics-okgrow-how-get-just-one-event

Thank you

**Comment by DonFabiolas** [comment]
So, I can see a weird behaviour with 'autorun'":false

**with this settings.json**

```
{
  "public": {
    "analyticsSettings": {
        "autorun"  : false,
      "Google Analytics" : {
       "trackingId": "XXX"
      }
    }
  }
}
```

=> In google Chrome Inspector Console, I do : "Meteor.settings" and I can see that "autorun:false" is not present

any Idea ?

**Comment by arrygoo** [comment]
@TroubadourFabiolas I think you're on the right path by setting `autorun:false` and setting your triggers manually. 

I just tried your settings and I had the same issue. Very peculiar. I will file this as a bug and investigate it further.

**Comment by ecwyne** [comment]
@arrygoo 
https://github.com/okgrow/analytics/blob/master/client/constants.js#L3-L4

It appears that the `Meteor.settings.public.analyticsSettings` are being passed as a reference rather than as a value. I don't see exactly where but it appears that when analytics.min.js [initializes](https://github.com/okgrow/analytics/blob/master/client/startup.js#L15) it somehow alters `Meteor.settings.public.analyticsSettings`.

I believe this issue may be fixed if `Meteor.settings.public.analyticsSettings` is passed by value rather than by reference.

This can be done as follows:

`client/constants.js`

``` javascript
const _settings = Meteor.settings && Meteor.settings.public && Meteor.settings.public.analyticsSettings;
const SETTINGS = _settings ? Object.assign({}, _settings) : false;
```

**Comment by pauldowman** [comment]
Thanks @ecwyne !!

**Comment by ecwyne** [comment]
Actually, I believe my prescribed solution would still have the same issue. `SETTINGS` would be altered by `analytics.min.js`.

A more robust solution would be to leave `client/constants.js` as is and pass a cloned object to `analytics.min.js`

https://github.com/okgrow/analytics/blob/master/client/startup.js#L15

``` javascript
analytics.initialize(Object.assign({}, SETTINGS));
```

That way `analytics.min.js` can modify the cloned settings without affecting other code that accesses the `SETTINGS` object

**Comment by ghost** [comment]
Check our latest release (v2.1.0) that includes a fix for this as well as a move to be "router agnostic".
