### ISSUE TITLE
prevent signin event

### ISSUE THREAD

**Issue by liortrench** [okgrow/analytics#145]
hi there!
we are using the accounts package which automatically track the sign in events. this is not good for our project as a meteor user is not a valid user on our system until it goes through an internal verification process. i want to trigger the signin/login event only after our verification process. is there a way to cancel the automated signup/signin event and control when to send it?
thank you.

**Comment by arrygoo** [comment]
Yes, setting autorun to false will disable the auto triggering of the app. Then you can trigger them manually, look at this for inspiration on triggering it yourself: https://github.com/okgrow/analytics/blob/0f677838c198b615a8918a00b890f959a8db9c7a/client/helpers.js#L11-L18

**Comment by liortrench** [comment]
@arrygoo thanks. setting autorun to false prevents event auto triggering except for the signin/login/signout events (from the okgrow documentation: 
"Log signin/signout If you have the accounts package installed, this package will automatically track when a user logs in and logs out. Logging in will call identify on the user and associate their Meteor.userId to their previous anonymous activities." 
my question was about disabling the the call to "identify". is that possbile?
thank you!

**Comment by arrygoo** [comment]
@liortrench from what I see there's currently no way to do that. The following code would need to be updated to use autorun: https://github.com/okgrow/analytics/blob/0f677838c198b615a8918a00b890f959a8db9c7a/client/meteor-analytics.js#L47-L62

**Comment by liortrench** [comment]
@arrygoo thank you!
