### ISSUE TITLE
Is it possible to pass user defined dimensions to GA? 

### ISSUE THREAD

**Issue by vadim-works** [okgrow/analytics#146]
I've added couple custom dimensions and trying to track them, so I need to send them from Meteor to GA.

Usually it can be done simply with:
```
var dimensionValue = 'SOME_DIMENSION_VALUE';
ga('set', 'dimension1', dimensionValue);
```

But I can't figure out is it possible to do the same thing with this package?

**Comment by cfnelson** [comment]
@vadim-givola Yes it is possible. This package is an extension of segment's analytics.js package. Check the documentation [here](https://segment.com/docs/integrations/google-analytics/#custom-dimensions).
