### ISSUE TITLE
Doesn't segment.com integration, by extension, allow this to integrate with most things?

### ISSUE THREAD

**Issue by HemalR** [okgrow/analytics#147]
I'm trying to integrate the drift.com chat widget into the site and having some issues:
* It works fine if I install it from scratch but
* If I instead pipe data into it using my segment.com account, then while it receives data, the chat widget does not come up.

So the question: Does this package's segment.com integration not allow segment/analytics.js to insert scripts into the app (i.e. Segment.com can only be used for data piping) or am I doing something wrong?

> If you use a different service for tracking events or page views and you think it's popular enough that we should add it then please open an issue on the repo and we'll see how many supporters we get.

This quote seems to suggest that the segment.com integration is not 'full' and I just want to make sure. 

Thanks for the very useful package and to anyone who can help shed light on the situation above!

**Comment by cfnelson** [comment]
@HemalR I am not 100% clear on your 1st question, this package hasn't modified segments analaytics.js package. If it is possible with their original one then it will be in this package if we support the integration.

In regards to your 2nd question, this package only supports a subset of the integrations that segment supports. You can see the list of integrations this package supports [here](https://github.com/okgrow/analytics#currently-supported-analytic-services).

**Comment by HemalR** [comment]
Cheers for taking the time to reply.

Yeah figured out that I would need to install analytics.js to give Segment the full capability to inject code into the app.

Thanks again.

**Comment by pauldowman** [comment]
@HemalR to clarify further, this package doesn't include client-side Drift integration. The Segment integration here will send data to the Segment service (assuming you have an account and have set it up to do so) and from there you use Segment as usual to forward that data elsewhere. So to answer your question "Doesn't segment.com integration, by extension, allow this to integrate with most things?" yes, it does allow you to send data to most things via segment, but doesn't provide any client-side support for other services except the ones listed on the README.
