### ISSUE TITLE
Not sending userId() in meteor app

### ISSUE THREAD

**Issue by ashwinthakre91** [okgrow/analytics#151]
938470516.1481857550 gettings this userId in GA which is not correct

**Comment by arrygoo** [comment]
@ashwinthakre91 Can you provide a minimal repo with this issue reproduced in it? You can use our examples as a starting point.

**Comment by ashwinthakre91** [comment]
Thank you very much for replay. Problem got solved😊

**Comment by srimenow** [comment]
@ashwinthakre91  I have this exact same issue, can you please share how you managed to fix? This is driving me crazy :(

@arrygoo I have this issue in both my projects, but will wait to hear from @ashwinthakre91 before trying to reproduce.

Are you using session unification? It's the only thing I can think of that would be throwing something off. It's either that or a lack of minifying which I will test next.

My Google Analytics Tracking code:
      "Google Analytics" : {"trackingId": "UA-**********-1", "sendUserId":true}

**Comment by ashwinthakre91** [comment]
In app settings define
"trackingId": "**********",
"sendUserId": true

If you are using mupx or mup to deploy meteor project.
Make sure you have provided these settings in settings.json or js file

**Comment by srimenow** [comment]
Thanks for the quick response, I had provided it in the deploy settings.json file except it was 
"Google Analytics" : {"trackingId": "UA-**********-1", 'sendUserId':true}

I just changed to "" and it should get everything working, I owe you a drink :)

**Comment by ashwinthakre91** [comment]
Haha...waiting for your call if you are in Bangalore, India.

**Comment by srimenow** [comment]
Just a quick update, it works! Really don't like how Google only let's you see one view or another so I am getting started on building my own Dashboard using Kibana. 

E-mail me, my_github_username@gmail.com, I'm in Bangalore every year and I love Mamagoto.

I'll leave these posts highlighting my incompetence up incase this helps another poor soul :)
