### ISSUE TITLE
Why is sensitive data like e-mail published to the client?

### ISSUE THREAD

**Issue by derwaldgeist** [okgrow/analytics#153]
I am using ```okgrow:analytics``` in combination with ```fastrender```. A user of my app just recently complained that it reveals sensitive data in the head of my app. I first could not believe it, but then I found out that in fact the e-mail address of the logged-in used could be found in fastrender`s injected data.

Since I was sure I was not publishing such sensitive information on my own, I tracked this down and eventually found out that ```okgrow:analytics``` is auto-publishing all e-mails it can find in the user profile:

https://github.com/okgrow/analytics/blob/0f677838c198b615a8918a00b890f959a8db9c7a/server/publications.js#L12-L15

Why is this necessary, and is there a way to prevent this publication?

**Comment by pauldowman** [comment]
It only publishes that to the user themselves. Not to anyone else. I don't think showing you your own email address is a security or privacy issue. 

It publishes the current user's email address to the client so that it can be used in an `identify` analytics call (which happens from the client side as do all analytics calls).

Please re-open if I have misunderstood something.

**Comment by derwaldgeist** [comment]
Thanks for your fast reply. Well, I understand your reasoning, but people here in Germany are quite concerned about data privacy. So finding their mail address in the source code (which was caused by combining your package with fast-render) made them suspicious. Anyways. I found out in the meantime that even Meteor's account package included an auto-publish for the mail address, so removing okgrow:analytics only removed the social media addresses, but not the main mail address. I even saw Arunoda's mail address in a screenshot while introducing fast-render.. Guess my users will have to live with that (or I have to drop fast-render so they won't see anything suspicious in the source code at least).

**Comment by derwaldgeist** [comment]
One additional question: You said that the mail address is used in identify() calls. I also saw in the docs that this function will be called on user login to enable identification of the user. Can I prevent this? I am only interested in anonymous analytics data. Or did I get something wrong?

**Comment by pauldowman** [comment]
This package calls `identify` with the various analytics services automatically and currently there's no way to customize that. I think we would probably accept a PR for adding that option.

**Comment by derwaldgeist** [comment]
Ok, thanks. Do you happen to know whether this will be called for Google Analytics? I looked at the repo, but found that the actual call resides in the vendor library analytics.js.

**Comment by pauldowman** [comment]
For Google Analytics it doesn't send personal info.

https://segment.com/docs/integrations/google-analytics/#identify

> It is against Google’s terms of service to pass Personally Identifiable Information (PII) to your Google Anlaytics reporting interface. For that reason Segment will never pass anything from an identify call to Google unless you specifically tell us to.
