### ISSUE TITLE
1.1.0 missing from atmosphere

### ISSUE THREAD

**Issue by avishaan** [okgrow/analytics#157]
1.1.0 seems to be missing from atmosphere, as a result I can't add that version 
![image](https://cloud.githubusercontent.com/assets/5360982/23966566/0dbce602-0979-11e7-86e9-393d679264c7.png)

**Comment by pauldowman** [comment]
Why do you want that specific version?

It is [tagged](https://github.com/okgrow/analytics/tree/v1.1.0) and the tag is created automatically by our publish script so I'm surprised it would not be on Atmosphere.

But I'm not sure there's anything we can do about it.

**Comment by pauldowman** [comment]
I think it might be that there was an issue with 1.1.0 and it was never published, but I can't remember. I'm assuming you can solve the issue by using a newer version and I'm going to close this.
