### ISSUE TITLE
My okgrow:analytics package is stuck at 1.0.9. Any ideas why?

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#158]
My okgrow:analytics package is stuck at 1.0.9. Any ideas why?

I even did `meteor remove okgrow:analytics` and `meteor add okgrow:analytics` and it still installs 1.0.9. Could it be that I'm depending on an old packages that doesn't allow the upgrade?

**Comment by pauldowman** [comment]
Yes it would be a dependency issue. Are you using at least Meteor 1.3.1?

**Comment by elie222** [comment]
Yes I am. I still use Iron Router. Is that an issue?

**Comment by cfnelson** [comment]
What version of Iron Router are you using?

**Comment by elie222** [comment]
1.1.2 which should be fine for the latest version of this package.

**Comment by cfnelson** [comment]
What happens if you run `meteor update okgrow:analytics` does it remain at the 1.0.9 version? You could always `meteor add okgrow:analytics@2.1.1` and then `meteor add okgrow:analytics` which would unconstrain the package from that version.

There is a PR open to remove the Router dependencies from the `package.js` which may help once its published. You can also take a look at the iron-router example to see it working on the latest version.

**Comment by elie222** [comment]
None of that works

**Comment by cfnelson** [comment]
Forgot to mention that you could also try running `meteor update --all-packages` to update any indirect dependencies you have. Not sure if you have already tried this? Also what version of Meteor are you on?

**Comment by elie222** [comment]
Okay I finally got it updated. It was an internal package of mine causing
the issues. It was stuck on 1.0.4 of this package as a weak dependency
which seems to have been the issue. Thanks for the help.

**Comment by pauldowman** [comment]
Awesome, glad you got it working.

**Comment by juliomac** [comment]
I also had the same issue, stuck on 1.0.9, but with a different solution and I hope this helps others.

I ran the following command to check for any package dependency:
```for p in `meteor list | grep '^[a-z]' | awk '{ print $1"@"$2 }'`; do echo "$p"; meteor show "$p" | grep -E '^  [a-z]'; echo; done```
Credit to this [answer](https://stackoverflow.com/questions/26153603/how-to-show-all-package-dependency-tree)

But found no dependency... Then I simply removed the package and added it again with:

     meteor remove okgrow:analytics
     meteor add okgrow:analytics

Just that simple.
