### ISSUE TITLE
Question: What's the difference between version 1 and 2 of this package?

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#161]
What's the difference between version 1.x.x and 2.x.x of this package?

**Comment by cfnelson** [comment]
@elie222 
- **v1.0.9** Doesn't use imports and is compatible with older meteor versions lower then 1.3.1
- **v2.0.0 and v2.0.1** switched to using imports and only supports Meteor v1.3.1 or higher, package still only supported flow-router and iron-router.
- **v2.1.0+** switched to being router agnostic and this is where the removal of using router `name` occurred. Package switched to using `document.title`

You could use **v2.0.1** and be safe to use `import { analytics } from "meteor/okgrow:analytics"` and still get the name event.
