### ISSUE TITLE
Analytics v1 page tracking in v2

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#162]
In version 1 of this package I would get pages views as follows:
`Viewed team Page`
`Viewed league Page`

In version 2 I get:
`View TITLE OF WEBSITE`

The problem is that every page on my site has the same title, so this new format is problematic. More than that, it only seems to log the first page load. All subsequent page loads aren't logged. I don't know if it's not logging the events, because the TITLE is the same for all the pages. Although 2 of the same events right after each other in other places doesn't cause this problem.

Any ideas how can I revert back to the old event naming easily? Or is the only solution using v1 of this package?

Thanks

**Comment by cfnelson** [comment]
@elie222 See my response to you here https://github.com/okgrow/analytics/issues/161 , in short use `okgrow:analytics@2.0.1` if you need the router `name`.

**Comment by ghost** [comment]
Yes we do have a bug in 2.1.x where name is not being properly passed. However, this will be fixed (shortly) to use document.title. As @cfnelson mentioned, if you rely on route name, stay with 2.0.1. If you are willing to set document.title for your pages you can use 2.1.3 (coming soon).

**Comment by ghost** [comment]
v2.1.3 Is published and fixes an issue where document.title was not being properly passed to the page tracking.
