### ISSUE TITLE
Update examples to have a unique `title` for each page

### ISSUE THREAD

**Issue by cfnelson** [okgrow/analytics#168]
Examples should be updated to have unique `document.title` for each page. Currently each page's `title` is set to [iron-router](https://github.com/okgrow/analytics/blob/master/examples/iron-router/iron-router.html#L2) or [flow-router](https://github.com/okgrow/analytics/blob/master/examples/flow-router/client/flow-router.html#L2) or [react-router](https://github.com/okgrow/analytics/blob/master/examples/react-router/client/main.html#L2). React Router example in v3 has done this: https://github.com/okgrow/analytics/pull/166

**Comment by ghost** [comment]
Wondering if we should close this now that v3 is officially out.
