### ISSUE TITLE
Global disable in certain conditions

### ISSUE THREAD

**Issue by Floriferous** [okgrow/analytics#173]
MixPanel provides an API to disable tracking like this: `mixpanel.register({"$ignore":true})`. Is there a way to do the same with the entire analytics package?

My specific use case is the following: I have 1 domain with 2 subdomains linking to the same app and server: www.app.com and demo.app.com. Going to the demo subdomain activates a demo mode for the app that lets the user quickly see what an active account looks like. It would be great if I could stop all tracking in certain conditions. Another use case for us is to disable it if the user logs in with a certain email address, from a particular domain (i.e. mike@internal-employee.com). 

If not, can I individually disable some analytics packages (mixpanel for example) through this package?

**Comment by cfnelson** [comment]
@Floriferous We only support a global disable for auto-tracking page views. You can read about in the ReadMe [here](https://github.com/okgrow/analytics#page-views), along with how to track page views or other events manually.

You can check out more detailed documentation on tracking with mixpanel [here](https://segment.com/docs/integrations/mixpanel/).
