### ISSUE TITLE
Issue with Modal

### ISSUE THREAD

**Issue by ycpatel813** [okgrow/analytics#174]
Hello, I found this is a very awesome module for Analytics. but I have a small issue in this.
I am using a model on my website and now I want to track model page opened closed.
so I have to add a manual page for an open model for that I have to use `"autorun"  : false`. But this will stop looking my normal page view. so is it possible to use both simultaneously?

Thank you.

**Comment by cfnelson** [comment]
@ycpatel813 Yes, you can do both. You just need to call `analytics.track()` as mentioned in the Readme [here](https://github.com/okgrow/analytics#event-tracking). You can find more detailed instructions [here](https://segment.com/docs/sources/website/analytics.js/#track).

All you need to do is call a `analytics.track` on your modal `open` & `close` events.

```
analytics.track("My Modal Opened", {
  eventName: "Modal Open",
  myCustomData: "Modal has been opened!",
});
```
```
analytics.track("My Modal Closed", {
  eventName: "Modal Closed",
  myCustomData: "Modal has been closed!",
});
```

**Comment by ycpatel813** [comment]
@cfnelson You are 100% right using `track` I can easily do that but if i need to check average time of modal open is this possible using that?
May be No. So I am creating virtual page for modal and set it.
Exp:
    analytics.page('Virtual/modal/XYZ');

For use of analytics.page, I need to use `"autorun" : false`. 
This is not looking my normal page view.
So i have opened this issue.

Hope you understand my problem.
Thanks for valuable replay.
