### ISSUE TITLE
autorun: false not disabling - still logging page views as events

### ISSUE THREAD

**Issue by lifeofjer** [okgrow/analytics#175]
I have elected to set _autorun: false_ to manually control Google Analytics Behaviors and Events. Objective is to log page views via Behaviors _and_ clicks, form submissions, payments via Events. Manual triggers are working as expected.

But, even with _autorun: false_ set in settings.json, the system still logs page views as Events. Cannot determine how to disable.

**Example GA Events**
<img width="1383" alt="screen shot 2017-05-07 at 8 32 40 pm" src="https://cloud.githubusercontent.com/assets/1686143/25789296/74c14edc-3364-11e7-81f5-387fe5e90c13.png">
<img width="1383" alt="screen shot 2017-05-07 at 8 33 04 pm" src="https://cloud.githubusercontent.com/assets/1686143/25789297/74c1d2d0-3364-11e7-91ac-64dbce2cb0d4.png">

**App settings.json file:**
```
"public": {
    "analyticsSettings": {
      "autorun": false,
      "Google Analytics": {
        "trackingId": "UA-xxxxxxx-10"
      }
    }
  }
```

**Manual Page View => Router {logPageView}:**
```
const logPageView = (nextState, replace) => {
      setTimeout( () => {
        analytics.page(document.title, {
          path: nextState.location.pathname
        });
      }, 200);
    }
```

**Manual Event Example => Payment Submission:**
```
analytics.track(event, {
     label: this.props.description,
     item: this.props.item,
    value: this.props.amount,
});
```

**Versions**
Meteor 1.4.4.2
okgrow:analytics 2.1.3

**Comment by ghost** [comment]
I have not been able re-produce this issue. But I want to be sure I understand it correctly.

When you set `"autorun": false` automatic page tracking is _still_ happening?

**Comment by cfnelson** [comment]
@jeremyccrane  We are going to close the issue as we have not been able to reproduce. Please let us know if you are still having problems.
