### ISSUE TITLE
Mixpanel Clarification

### ISSUE THREAD

**Issue by emilbruckner** [okgrow/analytics#178]
All data I see in Mixpanel is "Loaded a page"
Is this the expected behaviour? 
How would I setup tracking people?

Thanks

**Comment by townmulti** [comment]
+1 on this! Also for Mixpanel clarification, when loading data in a pagination event, I'm getting a `GET` http status code 414 (URI too Large) error in the console. Is there some way to truncate what's being sent to Mixpanel?

**Comment by cfnelson** [comment]
@emilbruckner Only pages are tracked by default. If you have meteors `accounts` package installed then this package will track signing in/out by calling `identify`. If you want to track custom events you will need to set that up yourself with `analytics.track()`. 

For more details on specifically mixpanel I would take a look at the doc's from segment.io for the [mixpanel](https://segment.com/docs/integrations/mixpanel/#getting-started) integration. Take a look at their examples for `identify` and `track` as well.

**Comment by cfnelson** [comment]
@townmulti How long is your URI? If the above error is for `analytics.page()` segment.io's `analytics.js` library automatically collects/sends the `title`, `path`, `url`, `referrer`, and `search`. You would have to override the properties automatically collected for the specific page causing you issues by hardcoding their values.  Example below

```js
analytics.page('MyPaginationPage', {
  title: 'Doc title for page',
  url: 'set my short url here',
  path: '/my-short-path',
});
```

Take a read of segment.io's specs for page [here](https://segment.com/docs/spec/page/#properties) and also their docs for the page event [here](https://segment.com/docs/sources/website/analytics.js/#page).
