### ISSUE TITLE
Integrating Google Optimize with this package

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#183]
Has anyone tried to integrate Google Optimize with this package?

Run into any issues? Or have pointers on how best to do it?

**Comment by cfnelson** [comment]
@elie222 We haven't personally set it up before, but you should be able to do it in the `analytics.ready()`, see segment.io's docs on [multiple trackers](https://segment.com/docs/integrations/google-analytics/#multiple-trackers). 

I would be curious to know how it goes ? Would be happy to have some additional documentation if you have been successful with it.

**Comment by cfnelson** [comment]
Closing, but we will be curious to hear about any updates. 😃
