### ISSUE TITLE
How to add more user info when user logs in?

### ISSUE THREAD

**Issue by znat** [okgrow/analytics#186]
By default, the package only logs `email` and `_id` when a user logs in. How can I add more fields such as name or first name?

**Comment by RichardLitt** [comment]
Good question. Where do you want the fields to be logged? In Meteor? 

You may be able to fire another event, and include any information in that. Alternatively, the email and _id will be associated to the Meteor.userId when `identify` is called, according to the README, so you could store the information with Meteor and use that. 

Someone else will know more. We'll get to the bottom of this as soon as we can.

**Comment by znat** [comment]
Thanks for replying so quickly!
The user signs up with a first and last name (added to the profile). I am using plain Accounts methods to create accounts and log in users. Is there a way to disable automatic identification so I could call `identify` myself?

**Comment by RichardLitt** [comment]
> Is there a way to disable automatic identification so I could call identify myself?

Good question. I am not sure. One of the other maintainers will know. We'll get back to you as soon as we can. :)

**Comment by alextondello** [comment]
I also don't now if we can disable the automatic identification, but in my app I do send more information about the user to Google Analytics, Amplitude and Intercom with success. You could do something like this on the client:

```
Meteor.startup(() => {
  Tracker.autorun(() => {
    if (Meteor.loggingIn()) return;

    const isLoggedIn = !!Meteor.user(); // Reactive

    if (isLoggedIn) {
      analytics.identify(Meteor.userId(), {
        phone: ...,
        email: ...,
        name: ...,
        role: ...,
      });
    }
  });
});
```

**Comment by cfnelson** [comment]
@znat There is currently no way to disable the automatic logging of the `sign in/sign out` events. We would be happy to accept a PR for this.

I believe @alextondello suggestion would be the best way to send additional information about your user. You will need to ensure any extra data you want to use has been published to the client.
We would be happy to accept a PR for something like this.

You could also use the `identifyWhenReady()` which comes from the [Auto Analytics](https://github.com/okgrow/auto-analytics) package, which this Analytics package extends.

**Comment by ghost** [comment]
Adding to @alextondello 's solution one could use `Accounts.onLogin()` callback to send this additional information. Thank you anyways, @alextondello .
