### ISSUE TITLE
Does this project support FB Pixel?

### ISSUE THREAD

**Issue by artgo** [okgrow/analytics#187]
If yes, how do I set it up? :)

**Comment by RichardLitt** [comment]
At the moment, it doesn't explicitly. No one has asked before. 

That doesn't mean it can't! Take a look at the code - if it seems like a pull request is possible, please open one. We'd be happy to look at it.

**Comment by pauldowman** [comment]
It doesn't right now because we are using a custom build of analytics.js which only supports a few of the most common integrations. But we're currently working on a way to use the full version with all integrations included (or a version that you build yourself with only specific ones).
