### ISSUE TITLE
Is there a way of disabling automatic identification?

### ISSUE THREAD

**Issue by jzabala** [okgrow/analytics#188]
Hi, is there a property or something like that to disable the automatic identification?

**Comment by cfnelson** [comment]
@jzabala There currently isn't in this package, if you don't want to do any automatic identification and only automatically track page views. Remove this package and use the base package [auto-analytics](https://github.com/okgrow/auto-analytics) that this package depends on. 
e.g -
`meteor remove okgrow:analytics` 
`meteor npm install @okgrow/auto-analytics --save`

We would be happy to accept a PR for this as well.

**Comment by jzabala** [comment]
Thanks for your response. 
I ended doing that.

**Comment by cfnelson** [comment]
@jzabala I should have mentioned if you want to see how to set it up in a Meteor App, check out the React Router example [here](https://github.com/okgrow/auto-analytics/tree/master/examples/react-router).
