### ISSUE TITLE
No data sent to Google Analytics

### ISSUE THREAD

**Issue by znat** [okgrow/analytics#189]
Hi,
I don't see any data on Google Analytics, but events are sent to Amplitude. 
Do you have any idea of what the problem could be?

```
{
  "public": {
    "analyticsSettings": {
      "Amplitude"        : {"apiKey": "..."},
      "Google Analytics" : {"trackingId": "UA-...-3", "sendUserId":true},
      "autorun"  : false
    }
  }
}
```

**Comment by cfnelson** [comment]
@znat Are you still having issues with Google Analytics? What happens if you remove the `"autorun": false`? Does GA work for you then? Are you potentially able to provide a minimal reproduction?
