### ISSUE TITLE
Does this work with React Router v4?

### ISSUE THREAD

**Issue by sergical** [okgrow/analytics#190]
Can't seem to figure out how to set it up 😢

**Comment by RichardLitt** [comment]
Good question! It looks like we don't have a guide for that, if the setup is different. Let's add that to the README when we figure it out. 

For now, I'm not sure if it does worth with React Router v4. Someone else here should be able to help soon.

**Comment by cfnelson** [comment]
@416serg v3+ of this package is router agnostic. It will work with any router (including react router v4+) and by default it uses the `document.title` as the page name for reporting to your analytics service.

You can follow a similar approach as suggested in the Readme, or use [React Helmet](https://github.com/nfl/react-helmet) which is what we have been using with React Router v4.

**Comment by RichardLitt** [comment]
I made a PR to add this to the documentat. @416serg Does this help?
