### ISSUE TITLE
Update analytics.js

### ISSUE THREAD

**Issue by dobesv** [okgrow/analytics#195]
The latest version of the analytics.js support Google Optimize by specifying the `optimize` parameter in the settings.  However, it doesn't appear that the current `okgrow/analytics` build has this.

https://github.com/okgrow/analytics.js/blob/master/analytics.js#L9205

**Comment by cfnelson** [comment]
@dobesv We have just published `v3.0.4` which includes an updated `analytics.min.js` it should include the latest version of the `Google Analytics` segment [integration](https://github.com/segment-integrations/analytics.js-integration-google-analytics).

Let me know if this latest version has solved the `optimize` parameter for you.

**Comment by dobesv** [comment]
I will give it a try when I can. Currently meteor won't let me update the
package, saying it is incompatible. So I'll have to solve that mystery
first.

**Comment by cfnelson** [comment]
@dobesv There shouldn't be any incompatible changes made going from `v3.03` to `v3.04`. The examples we have inside this repo are able to run without any issues. You could always manually set the version in `.meteor/.versions` and see if it runs ok. Hope your able to upgrade without any issues. 👌
