### ISSUE TITLE
Mixpanel integration not reporting on a specific project

### ISSUE THREAD

**Issue by abdelrahman-elkady** [okgrow/analytics#196]
I have Mixpanel integrated in multiple meteor projects, trying to integrate with some project that I am working on for a while seems to not be reporting any data. 

No errors on server/client is reported, using `3.0.1` because of the issue appearing with `meteor 1.5.2.2` in #179 with `3.0.2`

I am sure that `Meteor.settings.public.analyticsSettings.Mixpanel` is set correctly to `{ "token": "TOKEN", "people": true }` and is readable from client.

Tried `analytics.debug()`, and tried sending events directly from the console. Nothing yet is reported to mixpanel.

#### Meteor version: 
`1.5.2.2`

#### Packages:

```
meteor-base@1.1.0
mobile-experience@1.0.5
mongo@1.2.2
blaze-html-templates@1.0.4
reactive-var@1.0.11
reactive-dict@1.1.9
jquery@1.11.10
tracker@1.1.3
standard-minifier-css@1.3.5
es5-shim@4.6.15
ecmascript@0.8.3
shell-server@0.2.4
session@1.1.7
allow-deny@1.0.9

check@1.2.5
random@1.0.10
accounts-base@1.3.4
accounts-password@1.4.0
underscore@1.0.10
email@1.2.3
deps@1.0.12
templating@1.2.14_1
ejson@1.0.14
npm-bcrypt@0.9.3

utilities:avatar@=0.9.2
kadira:flow-router@=2.12.1
kadira:dochead@=1.5.0
aldeed:collection2@=2.10.0
dburles:collection-helpers@=1.1.0
fourseven:scss@=3.8.1
maibaum:foundation-icons@=0.0.1
zurb:foundation-sites@=6.3.0
fortawesome:fontawesome@=4.7.0
nimble:restivus@=0.8.12
alanning:roles@=1.2.16
underscorestring:underscore.string@=3.3.4
yuukan:streamy@=1.4.0
themeteorchef:bert@=2.1.1
meteorhacks:ssr@=2.2.0
meteortoys:allthings@=4.0.0
kadira:blaze-layout@=2.3.0
cfs:standard-packages@=0.5.9
edgee:slingshot@=0.7.1
arillo:flow-router-helpers

dispatch:mocha@=0.4.1
xolvio:cleaner@=0.3.1
dburles:factory@=1.1.0
hwillson:stub-collections@=1.0.3
practicalmeteor:mocha@=2.4.5_6

abpetkov:switchery@=0.1.0

rajit:bootstrap3-datepicker
peerlibrary:aws-sdk
dynamic-import@0.1.3
standard-minifier-js@2.1.2
rafaelhdr:google-charts
mizzao:jquery-ui
okgrow:analytics@=3.0.1
```

**Comment by cfnelson** [comment]
@abdelrahman-elkady Do you see any events being fired when you have enabled `analytics.debug()`? Don't forget to refresh browser after you enabled `analytics.debug()`.
 
You should at least see the analytics get initialized or a warning/error if it doesn't?

You can also run one of the included examples in this repo to see GA + Mixpanel working. Are you by any chance only using `Mixpanel` or with any other services?

**Comment by abdelrahman-elkady** [comment]
@cfnelson Nothing fired when `analytics.debug()` is enabled, actually, things are really weird, in other projects, when I remove the key from `settings.json` it fires a warning in the console, tried this and nothing is showing too !

The same exact mixpanel project ( the same key ) is working fine on other projects ! but in this specific project it is not, not sure if it is something related to the package set in this project ...

**Comment by desoukya** [comment]
@abdelrahman-elkady is it possible to reproduce this behavior by creating a separate repo/project with the same exact meteor version and packages? If so, this could be useful for debugging the issue.

**Comment by abdelrahman-elkady** [comment]
@desoukya unfortunately, it is working with the same packages on a bare project, and even with the exact `settings.json` structure

**Comment by abdelrahman-elkady** [comment]
Bug found, this was happening because some other package sets `window.onload`, this must be documented somewhere, it is only documented here: https://github.com/okgrow/auto-analytics/blob/81bd954507f8c25c10a8c55f5d3074b3774f7f46/src/index.js#L100

**Comment by cfnelson** [comment]
@abdelrahman-elkady Thanks for the update, did you determine which package was the cause? I am guessing the other package is overwriting our `window.onload` function without calling any of the functions already applied. We may look to change this behaviour ourselves or at least add better documentation to the Readme.
