### ISSUE TITLE
Using Analytics Package with Flurry and Multiple API Keys

### ISSUE THREAD

**Issue by bryanterrell** [okgrow/analytics#20]
This may or may not be an issue, as I haven't actually started using the package yet. The reason being that we were looking at using Flurry, which requires different projects (and API keys) for different mobile platforms. We are currently building our Meteor app for iOS and Android, which means I have a unique Flurry project and API key for each.

I saw that @pauldowman mentioned something about potentially being able to configure Analytics via JS in another issue (https://github.com/okgrow/analytics/issues/3), which I think would address this scenario since we could configure the package on startup based on whether it was an Android or iOS client.

And if there is another solution I'm just not seeing please let me know. Thanks!

**Comment by tsemana** [comment]
thanks @bryanterrell. Have you made the decision on Flurry at this point? Our package uses a subset of of this [analytics-integrations](https://github.com/segmentio/analytics.js-integrations/tree/master/lib) library and unfortunately Flurry does not have an implemented integration.

It sounds like the decision is not yet concrete and if so I'd suggest looking at the list of supported services. Closing this ticket in the meantime.

**Comment by pauldowman** [comment]
Weird that they don't have flurry because Segment does support it. I guess just server-side.

**Comment by bryanterrell** [comment]
Our marketing director requested we try to get Flurry working - from what I've read it's the leader in mobile analytics and guessing that Yahoo will push it even more. Thanks for clarifying, though - I just assumed it was supported by the JS library because it was listed as one of the Segment integrations.
