### ISSUE TITLE
App crashes with ad blocker

### ISSUE THREAD

**Issue by nicooprat** [okgrow/analytics#200]
Getting a blank page and this error when navigating on my app on Safari iOS 11:

![image](https://user-images.githubusercontent.com/645641/31575430-1ce0f7e8-b0e7-11e7-9a78-7653e46baca5.png)

My content blocker (Purify) is in cause. Reloading without it works.

Any idea how to avoid this? Thanks.

Edit: same on Chrome desktop (Mac OS) when using Ublock.

**Comment by nicooprat** [comment]
Didn't see https://github.com/okgrow/analytics/blob/3c056a95f63fb23ce1ccd3c4f72f46516e657bce/README.md#ad-blocker. My bad.

**Comment by RichardLitt** [comment]
Thanks, @nicooprat, for logging anyway! Others may run into this issue in the future.
