### ISSUE TITLE
GDPR compliance for Google Analytics

### ISSUE THREAD

**Issue by derwaldgeist** [okgrow/analytics#208]
Hi, as of May 25th, analytics has to be compliant to GDPR regulations in the EU.

At the bare minimum, this requires:
- the user to be able to opt out of analytics. This can be done by either installing a browser plugin or - for mobile devices - with a browser cookie, as described here: https://developers.google.com/analytics/devguides/collection/gajs/?hl=de#disable
- setting the anonymizeIP option: https://support.google.com/analytics/answer/2763052?hl=en

Is there a way to enable this with `okgrow:analytics`? Otherwise, I would have to disable analytics in my apps.

**Comment by derwaldgeist** [comment]
Update: For anonymizeIP, I found #38, so this should be covered.

**Comment by RichardLitt** [comment]
@pauldowman If you're not aware of this already, probably could use your feedback. :)

**Comment by cfnelson** [comment]
@derwaldgeist I believe you found the answer which you linked to? As seen below. 

```
"public": {
    "analyticsSettings": {
      "Google Analytics" : {"trackingId": <ga-id>, "anonymizeIp":true}
    }
}
```

Were you still looking for feedback on the first point? If your wanting greater control you can use our [@okgrow/auto-analytics](https://github.com/okgrow/auto-analytics) which is an npm pkg and gives you more control on when/how you initialise your analytics. e.g -> don't initialise if your user declines your tracking. The package doesn't track meteor.login events as well and it's router agnostic.

cc @RichardLitt

**Comment by derwaldgeist** [comment]
Thanks for the fast replies. Yes, I was still looking for feedback on the first point. But I was able to implement this on my own in the meantime, by setting the global variable as described in the Google article. Luckily, this affects `okgrow:analytics`, too, and Google stops tracking immediately. And, also important, It won't restart it again on app reload. This workaround is a bit ugly, because it clutters your global namespace, but it works. So I'm closing this.
