### ISSUE TITLE
Tag not found

### ISSUE THREAD

**Issue by carlovenus** [okgrow/analytics#209]
Hello there,

i am unable to get it work. Analytics and Google Tag Manager tell me that the tag is not found, although the analyticsSettings are set properly.  

`"public": {
        "analyticsSettings": {
            "Google Analytics": {
                "trackingId": "XYZ"
            }
        }
    }`

I am using Iron Router without setting

`Tracker.autorun(() => {
    document.title = Router.current().route.getName();
  });`

Is it mandatory for the package to work correctly?

**Comment by cfnelson** [comment]
@carlovenus Your meteor settings look correct. Check out our [Readme](https://github.com/okgrow/analytics#iron-router) which states how this works with iron router (code snippet below) & I would also recommend taking a look and running the `iron-router` [example](https://github.com/okgrow/analytics/tree/master/examples/iron-router) that we have in the repo.

```js
Template.mainLayout.onRendered(function() {
  Tracker.autorun(() => {
    document.title = Router.current().route.getName();
  });
});
```

If you want a router agnostic analytics, you could use the npm pkg [@okgrow/auto-analytics](https://github.com/okgrow/auto-analytics) though it wont track meteor logins etc. 

Let me know if this has helped or resolved the issue for you. 😃
