### ISSUE TITLE
How to supply our own analytics.js build?

### ISSUE THREAD

**Issue by promentol** [okgrow/analytics#212]
I saw inside v4 branch, that it is getting planned to support own analytics.js build. What is the steps to integrate our ready to use analytics.js build?

**Comment by cfnelson** [comment]
@promentol If you're wanting to use your own analytics.js build I would recommend switching over to this pkg https://github.com/okgrow/auto-analytics , only missing feature is the meteor specific user/login tracking. You can then use your own build. Read the `Creating Segment's analytics.js` section in the Readme for the instructions your looking for. 
Hope this helps :)
