### ISSUE TITLE
Make the automated user tracking optional

### ISSUE THREAD

**Issue by oskarszoon** [okgrow/analytics#26]
I understand this behaviour is desired when accounts-base is used, but in our case we want a little bit of extra control over it. Constant "Signed in" events are when the user first loads the page, which makes sense in Meteor, but does pollute the data a bit.

I would prefer to be able to turn this off through a configuration.

**Comment by oskarszoon** [comment]
Another thing is the auto-identify which doesn't make sense for our users setup (encrypted profiles). We now add the identifying info on analytics.ready(), which means the first "Signed in" event fires with the automatic identify (which again is incorrect in our case)

**Comment by pauldowman** [comment]
@oskarszoon are you using version 0.2.5? Prior to that there was a bug where signed in events could fire on page load, but I don't think that should happen now. Does that address your first issue?

And I don't fully understand your second comment, can you explain? It should only identify on sign in. Is there ever a case where you wouldn't want to identify on sign in? I don't think so. Why would you identify on analytics.ready()? That would cause it to happen on every new load of the app, which I don't think is what you would want.

**Comment by oskarszoon** [comment]
@pauldowman The new version definitely helps, but I still think it's weird that a "Signed in" event is fired every time a user opens the app or reloads the page. It would make more sense to fire a "Meteor loaded" event, and only fire Signed in when he actually signs in for the first time (which we're tracking now manually).

As for my identify issue, the situation we have is that we want to change the identifier of the events to something that is only available in the user profile once decrypted in the client. This means that the identifier we want to use (so not userId) isn't available until later, that's why we chose to use analytics.ready (and our own ready handler before that). With autotracking enabled it will first throw an event with the regular userId as the identifer, and then once our system is loaded it uses a different identifier, causing duplicate records in our analytics tool.

So, in a more general sense: it would be nice to be able to easily toggle the autotracking feature. To prevent too many Signed in events and also to be able to better configure the identifier.
