### ISSUE TITLE
package causes client errors

### ISSUE THREAD

**Issue by ChenRoth-old** [okgrow/analytics#28]
hey

I added your package to my project and configured Meteor.settings to include a GA key
However, once the package is added, my app is broken

I get this warning in console (I have iron:router):
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?

I know your code calls this.next(), but something seems to be broken
Anyway, the program execution gets cut and its indication is parts of my app produce errors (unknown variables etc)

I don't really know how we can help each other with that, as I can't isolate the problem

UPDATE:

the minute I opened the issue, I think I figured where the problem is...
in my project, I use a transform function for my users collection, which leads to various code executions
My guess would be your package runs first, calling Meteor.user()  and in turn invokes the transform function. As your package runs before other init code is executed, this leads to complications
The workaround may not be trivial (tinkering with load order, if possible at all), so I think it should be made clear to other people

**Comment by tsemana** [comment]
@ChenRoth Thanks for the update. Were you able to pin-point specific interaction?

**Comment by ChenRoth-old** [comment]
yeah, it's basically what I presumed - your package runs a Meteor.user()
call at a very early stage, which invokes my custom transform function on
the users collection.
not sure if you're up for this change, but I guess a viable solution would
be to allow optional override of the transform function (or pass a null
argument to bypass it altogether)
