### ISSUE TITLE
wrong page tracking

### ISSUE THREAD

**Issue by ChenRoth-old** [okgrow/analytics#30]
hey @tsemana, 

following specific requirements in my project, I've decided to write my own analytics wrapper (which also includes a server-side analytics-node wrapper, btw)

Naturally, I've mentally borrowed basic ideas from your project, such as running a page track within an onRun event (originally suggested by the Iron Router author, of course)

However, I've realized that page tracks are inaccurate, as the recorded url & path in a page track call are actually of the preceding url to the one you track

to fix that, I've wrapped the page track in a Tracker.afterFlush:

```
Router.onRun(function() {
var router = this;
Tracker.afterFlush(function() { analytics.page(router.route.getName()); // etc });
this.next();
})
```

this way, it's guaranteed the right url is recorded

**Comment by tsemana** [comment]
@ChenRoth thanks for the pointer. Made the update in the latest commit.
