### ISSUE TITLE
Flow Router Support

### ISSUE THREAD

**Issue by hpx7** [okgrow/analytics#31]
Could we get support for flow-router as well?

**Comment by tsemana** [comment]
@hpx7 yes. It's already been discussed internally as an upcoming feature.

**Comment by nikhildaga** [comment]
+1

**Comment by thirdchance57** [comment]
so i guess there is okgrow will not work with flow router?

**Comment by tsemana** [comment]
@thirdchance57 - Not exactly sure what the comment means, but feel free to check the pending PR here: https://github.com/okgrow/analytics/pull/37

**Comment by tsemana** [comment]
The most recent update has support for flow router. There is also an example app included in the repo under the examples folder.

**Comment by cpury** [comment]
@tsemana better add it to the readme! :) Aside from the example and the commit message I wouldn't have figured out that there's flow router support.

**Comment by cpury** [comment]
Sorry, one more question. I'm trying to get this to run with Flow-Router. When debugging, I can see all the events I manually track with `analytics.track()`, but Flow routing changes don't seem to trigger anything.

Did I miss a step? It seems in the example you're not doing anything special to get it to run automatically with flow router...
