### ISSUE TITLE
GET net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by geritol** [okgrow/analytics#32]
Hi!
I am getting this error:

GET http://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT

Do you know why does it happen or how to solve it?
Thanks a lot!

**Comment by geritol** [comment]
Just found the answer: the problem was Ad Block (on chrome)...

Don't know if we can do something about it, but currently this plugin wont let you track users or visitors using Ad Block.

http://stackoverflow.com/questions/22318119/i-am-getting-failed-to-load-resource-neterr-blocked-by-client-with-google-chr

**Comment by noahsw** [comment]
This is preventing my entire Meteor app from loading. I just get a white screen with a bunch of console errors:
![image](https://cloud.githubusercontent.com/assets/2034879/18333022/1d273040-7520-11e6-8af4-57a609720610.png)

My only workaround is to disable adblock. This is a blocker for me using this package unfortunately.

**Comment by cfnelson** [comment]
@noahsw Is this happening in dev or production mode ? Is this the issue referred to in the [README](https://github.com/okgrow/analytics#ad-blocker) ? If it's not can you please provide more information and/or a minimal reproduction as we have tested on our example apps without any issues when following the README instructions.

**Comment by noahsw** [comment]
Ah, you're right @cfnelson. I didn't see the note on the README. However, I think we should make it clearer that the key difference is minification. I use meteor-up and I'm able to deploy to production (with Meteor.isProduction true), _without_ minification. That's where I was getting the error.

Once I minified things with meteor-up's `buildOptions { debug: false }`, everything was fixed.

**Comment by arrygoo** [comment]
@noahsw I agree with your point about minification being clearer in the guides. Will add that. 👍

**Comment by pauldowman** [comment]
Is it the package name that's a problem, or one of the file names? Is it possible to rename something? (Maybe not if it's the package name itself).

**Comment by noahsw** [comment]
Thx @arrygoo ! 

@pauldowman, I believe it's because the javascript file it exports has the word "analytics" in it.

**Comment by cfnelson** [comment]
@noahsw Sorry for the late response, been away on holiday. You are correct that it's due to it not being bundled. 

@pauldowman It is due to the Package name that we are using. I believe uBlock is inspecting the Request URL and/or its response and blocks if it reads the word "analytics". When the Meteor packages are not bundled Meteor requests each package individually. In our case something like this `http://localhost:3000/packages/okgrow_analytics.js?hash=4a8c92364e5f2ab889a06fd2f25d06330856e73e`

**Comment by calebkleveter** [comment]
I got this because I was running AdGuard. After turning it off things started working!

**Comment by Arnauw** [comment]
Just had this problem too with "https://apis.google.com/js/platform.js", only solution is to disable addblock, or maybe charge the script locally instead.

**Comment by AlmTalal** [comment]
> Just had this problem too with "https://apis.google.com/js/platform.js", only solution is to disable addblock, or maybe charge the script locally instead.

How can i disable the add blocker in a vite-react project? I'm having the same issue when deploying locally
