### ISSUE TITLE
analytics.initialize is not a function ?

### ISSUE THREAD

**Issue by rkstar** [okgrow/analytics#33]
i added the okgrow:analytics package and updated my settings.json using the example provided, but i'm getting an error when running my app.

```
Error: analytics.initialize is not a function
TypeError: analytics.initialize is not a function
    at http://localhost:3000/packages/okgrow_analytics.js?bf33fbe0c5894de7177a754bf4c090a67b7fe529:36:15
    at runStartupCallbacks (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:785:22)
    at HTMLDocument.ready (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:787:3)
```

`settings.json`

```
  "public" : {
    "analyticsSettings": {
      "Mixpanel": {
        "token": "<my_token_here>",
        "people": true
      }
    }
  }
```

**Comment by tsemana** [comment]
@rkstar, sorry you're running into the issue. I can't reproduce the error without more information. Can you add me to your repo or setup an example repo doing the same thing?

**Comment by rkstar** [comment]
it seems i had `percolatestudio:segment.io` package installed also which i suppose was conflicting with its own version of analytics.js.

i did get another problem though, using flow-router, i'll open another issue.
