### ISSUE TITLE
Error on Local Environment

### ISSUE THREAD

**Issue by nicholasalanbrown** [okgrow/analytics#35]
Hello:

Despite following the instructions and placing the trackingID inside a "public" block in my settings.json, I still get an error when developing on my local in the browser console:

```
Missing analyticsSettings in Meteor.settings.public
```

However, the tracking seems to work just fine in production. This is my settings.json block:

```
   "public":{
      "analyticsSettings":{
         "Google Analytics":{
            "trackingId":"UA-XXXXXXXX-X"
         }
      }
   },
```

**Comment by tsemana** [comment]
Hi @nicholasalanbrown, Just a simple check, but are you starting meteor with `meteor --settings setting.json` ?

**Comment by tsemana** [comment]
@nicholasalanbrown, any update on this issue? Could you give us more details that might help us reproduce the issue?

**Comment by nicholasalanbrown** [comment]
Yes, thanks @tsemana I got it working with your suggestion. I'll probably skip starting that way on my local though since it's not annoying. I wish Meteor had a better built in system for managing environment-specific settings/variables.

**Comment by tsemana** [comment]
Ok, good to hear. Closing this ticket
