### ISSUE TITLE
ga anonymize IP

### ISSUE THREAD

**Issue by thomasspiesser** [okgrow/analytics#38]
hey guys,
thanks for the convenient package. quick question: i need to anonymize the IP through `ga('set', 'anonymizeIp', true);` in google analytics. can I do that using this package? if yes, how and where would be the best place?

**Comment by deanrad** [comment]
Sorry for the delay - I assume you've figured out something by now - would you mind sharing it ?

**Comment by thomasspiesser** [comment]
hey, no problem. actually i haven't..

**Comment by deanrad** [comment]
So, the question is -how, with this package, does one get access to the `ga` object that analytics.js usually exposes ? Good question :)

**Comment by benstr** [comment]
@thomasspiesser give this a try:

```
"public": {
    "analyticsSettings": {
      "Google Analytics" : {"trackingId": <ga-id>, "anonymizeIp::true},
      "Mixpanel"         : {"token":  "891dca8a6b8138412cd4001f63658da6", "people": true}
    }
  }
```

Reference: https://github.com/segmentio/analytics.js/commit/ef43fa11c3108c6360bd952ede34aaae661bc6ab

**Comment by benstr** [comment]
@thomasspiesser give this a try:

**settings.json**

```
"public": {
    "analyticsSettings": {
      "Google Analytics" : {"trackingId": <ga-id>, "anonymizeIp":true}
    }
}
```

Reference: segmentio/analytics.js@ef43fa1, https://github.com/segmentio/analytics.js/blob/master/analytics.js#L12889

**Comment by thomasspiesser** [comment]
hey ben, 
thanks for the response.
cheers,
thomas
