### ISSUE TITLE
Mixpanel does not receive data from analytics.identify()

### ISSUE THREAD

**Issue by alexzaporozhets** [okgrow/analytics#4]
We are using [accounts-ui-bootstrap-3](https://atmospherejs.com/ian/accounts-ui-bootstrap-3) package.

**Comment by alexzaporozhets** [comment]
I solve the problem - extra boolean parameter was required.

```
"Mixpanel":{"token":"...", "people":true }
```

But still it will work only for local account (email/password). For facebook & google we need to program extra.

**Comment by tsemana** [comment]
Hi,

thanks for pointing that out. I'll update the README to include `"people": true` in the settings. As for oauth identify requiring extra work, that's correct and intentional. We only handled email/password initially because most apps use this by default but not all apps use oauth.
