### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by cyllu2** [okgrow/analytics#43]
I added the package, added the settings inside settings.json, doesn't work. My tracking code is correct and I've waited about 24 hours now for Google Analytics to respond. Nothing happens. Is there something else I need to do? (Yes, I use Iron Router).

**Comment by nicolamr** [comment]
Is the "analytics" object available to you? Client or server side? I just installed it and there's no analytics object (don't know if it's supposed to exist both server and client side). Maybe we have the same issue?

**Comment by tsemana** [comment]
Hi @cyllu2, @nicolamr, just spooled up a scaffold app and tested latest build and meteor versions and I'm seeing activity immediately in the realtime section of GA. Just looking for a little more information on the issue.

- Are there any errors showing up in the console?
- Are you starting meteor with `meteor --settings settings.json`?
- What's displayed in the console when you turn on debug in the console? (`analytics.debug()` and reload the app)

Thanks for the info.

**Comment by cyllu2** [comment]
It took another 24 hours (so two days) for it to start, that's all. Sorry for the confusion, but damn that was slow.

**Comment by tsemana** [comment]
No problem @cyllu2, thanks for the update
