### ISSUE TITLE
The publish function wipes out other projections I have 

### ISSUE THREAD

**Issue by adamgins** [okgrow/analytics#45]
The publish Users function, uses the following projection:

```
{fields: {  'services.facebook.email': 1,
                  'services.google.email': 1,
                  'services.github.email': 1 }});
```

https://github.com/okgrow/analytics/blob/master/lib/server/publications.js

For example, if I had to get `services.facebook.<some other attribute>`

I need to get additional fields for my user record, so this publish wipes them out.

Is there some way to workaround this please?

**Comment by tsemana** [comment]
@adamgins - thanks for pointing this out. We think it might be a bug in how meteor handles sub-documents specified in separate publications. I'm going to create a meteorpad and submit a bug on meteor.
In the meantime unfortunately it looks like you might need to include the package source in your codebase and modify it to remove the facebook field from the package and ensure you include `services.facebook.email` in your project publication.
Please let me know if you find a different workaround. I'll link to this issue when I submit the meteor issue.

**Comment by adamgins** [comment]
@tsemana thanks. yep had already copied the package and hacked it. 

I think this is how Meteor just works/should work (I may be wrong/too accepting)... I had a similar issue the other day where I could not understanding why I had a publication that published some fields, yet they weren't on the client. The reason is I was publishing the same document via another subscription and it was overwriting the same document with the additional fields... I think this is probably correct, it just means you need to be super careful when you have subscriptions with different projections for the same documents... I guess last/latest doc wins.

**Comment by deanrad** [comment]
I don't know if there's anything we can do about this - short of detecting existing publications and merging them ? I don't know if that's a) possible or b) a widespread problem. But I agree that it's an issue.

**Comment by dan335** [comment]
The meteor docs talk about this under Meteor.subscribe.  Here's a workaround.

```
if (Meteor.isClient) {
  AnalyticUsers = new Mongo.Collection('analyticusers');
}

if (Meteor.isServer) {
  Meteor.publish(analyticsUsers, function() {
    var self = this;
    var query = Meteor.users.find({_id: this.userId}, {fields: {'services.facebook.email':1});
    Mongo.Collection._publishCursor(query, self, 'analyticusers');
    return self.ready();
  })
}
```

Publish from users to a client only collection.

**Comment by benstr** [comment]
Awesome, thanks @dan335. I am planning to tackle this issue soon. But if you beat me to it just send a PR and I will make sure to get it merged.
