### ISSUE TITLE
Initialisation/timing issues?

### ISSUE THREAD

**Issue by tomwasd** [okgrow/analytics#47]
Hi,

Firstly, great package - thanks a lot for making it.

I'm using the package with Flow Router 2.0.0 as per the PR I submitted so apologies in advance if this issue is specific to that although I think it might apply to older versions of Flow Router too.

There seem to be two issues/bugs:
1. On initial page load analytics.js doesn't seem to have initialised and so the first page view isn't tracked.
2. Moving between routes the previous URL is sometimes reported as the current URL.

I'm basing the above on what analytics.debug chucks out.

I've managed to patch both of these issues by wrapping the reporting code in a timeout:

```
Meteor.setTimeout(function() {
  if (context.route && context.route.name) {
    analytics.page(context.route.name);
  } else {
    analytics.page(context.path);
  }
}, 500);
```

But that seems a bit hacky! I was just wondering if anyone else had any ideas as to how to resolve the issue?

Thanks,

Tom

**Comment by tsemana** [comment]
@tomwasd - thanks for pointing this out and for the PR, we'll take a look at both asap.

**Comment by wehrlock** [comment]
For second issue, how about overriding the analytics data for title and path using the router context?

```
if (context.route && context.route.name) {
  analytics.page(context.route.name, {
    title: context.route.name,
    path: context.path
  });
} else {
  analytics.page(context.path, {
    path: context.path
  });
}
```

**Comment by pauldowman** [comment]
I'm confused about the status of this. It sounds like a bug, or two bugs, but it's labeled "question". 

Is the second issue closed? And the first one still open?

I'm going to remove the "question" label.

**Comment by benstr** [comment]
This is a dup (or the other is a dup) of #58. @pauldowman I am working on a solution that will cover both issues.

**Comment by pauldowman** [comment]
Version 1.0.1 released. This problem should be fixed, let me know if you still see it.
