### ISSUE TITLE
Data seems to be one page behind

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#5]
I added this package to my site and ran analytics.debug() in the console.

When I jump from page to page, I'm getting data such as this:

```
properties: {
  name: "howToPlay",
  path: "/transfers",
  ...
}
```

This is data I get when I go from the transfers page to the howToPlay page. (The path for the howToPlay page is "/howToPlay". And the page for the transfers page is "/transfers").

**Comment by jhmacdon** [comment]
This happens to me also

**Comment by tsemana** [comment]
I'm sorry about not getting to this sooner. Can you tell me if you're still experiencing the problem? I have not been able to reproduce the behaviour. 

We've just pushed an update, if you're able to try it and let me know or if you could add me to a repo where this is happening?

Thanks for your help!

**Comment by tsemana** [comment]
@elie222 I'm closing this for now but feel free to re-open it if you can confirm that you're still experiencing the problem?

**Comment by ycpatel813** [comment]
Hello tsemana I am also facing same issue.
If you want to produce this issue just run flow-router example with `autorun:false` in settings.json.
Add analytics.page('PAGE') in flow.router.js.

Thank you.
