### ISSUE TITLE
How can I send the userId to Google Analytics?

### ISSUE THREAD

**Issue by dkleiman** [okgrow/analytics#54]
I've set up a dedicated userId view in Google Analytics (GA), yet I haven't been able to see any activity from logins and logouts even though the package automatically calls identify with the userId. I suspect this is because analytics.js doesn't automatically send any user info to GA on identify. Has anyone managed to do this? 

I'm also using the GA debugger extension for Chrome, and it looks like the uid is never being sent.

**Comment by pauldowman** [comment]
I think analytics.js does send use rid info to Google on identify. The most recent version does anyway. 

Can you give us steps or ideally sample code to easily reproduce it?

**Comment by dkleiman** [comment]
I just set up a dedicated view in Google Analytics to view user data, and since the package automatically calls identify on login, I figured I would start seeing data in the Realtime reporting tab in GA when a user logs in. Since that didn't work, I tried calling <code>identify</code> setting <code>{integrations:{"Google Analytics": true}}</code> in the callback of the <code>Meteor.login</code>, but that also didn't work. All of the usual data like pageviews was being sent to GA and I could view it, but not the user data.

I think the problem might be related to analytics.js not sending user data to GA without it being explicitly specified. 

It says <a href="https://segment.com/docs/integrations/google-analytics/">here</a> that "Segment will never pass anything from an identify call to Google unless you specifically tell us to."

I have since switched to using a simpler package that only handles GA, and I can see the uid.

**Comment by benstr** [comment]
@dkleiman thanks for all the research. It turns out this option can be configured through your settings.

```
'public': {
    'analyticsSettings': {
      'Google Analytics' : {'trackingId': <ga-id>, 'sendUserId':true}
    }
}
```

Reference: https://github.com/segmentio/analytics.js/blob/master/analytics.js#L12900

**Comment by KristerV** [comment]
does this send the Meteor.userId() automatically then?

**Comment by steven-tib** [comment]
I'm trying to get the userId (Meteor.userId()) sent to google analytics but doesn't seem to work. I've followed the different suggestions above but still not working. Isn't it necessary to specify a new "dimension" for the custom user id? 
@dkleiman what is the simpler package that you are now using, which works with userIDs?

**Comment by steven-tib** [comment]
Ok, it was actually properly saving the data linked to each user, and found the way to display it.
By configuring properly my views in google analytics I was able to show the analytics per userId. 
more info here: https://support.google.com/analytics/answer/3123666?hl=en&ref_topic=3123660

**Comment by pauldowman** [comment]
I'm glad you got it figured out!
