### ISSUE TITLE
Publication Conflicts With User Services Publications - Breaks App For Facebook

### ISSUE THREAD

**Issue by redwraith2** [okgrow/analytics#57]
https://github.com/okgrow/analytics/blob/master/lib/server/publications.js

The publications page is a serious issue for anyone who requests data because of this issue:
https://github.com/meteor/meteor/issues/3764
I can't request anything from 'services.facebook' or 'services.instagram' at all because of this.

It breaks the avatar package, as well as blocking me from being able to get social info other than email generally. This is a big problem. Until Meteor fixes this, please add an explanation to your main page to add a publish request.

**Comment by jfly** [comment]
A _BIG_ :+1: on this. It took me a very long time to figure out why I was having trouble publishing any information from the `services` subdocument.

**Comment by pauldowman** [comment]
Yes. Let's brainstorm solutions. Any ideas? Can/should we publish those emails under some other publication? Or make it optional?

**Comment by jfly** [comment]
Opting out sounds simplest, and would definitely work.  Just making another subscription won't help, right? Or were you suggesting publishing to client side collection that isn't `Meteor.users`? My understanding is that the `Mongo.Collection._publishCursor()` method described [here](https://medium.com/@MaxDubrovin/workaround-for-meteor-limitations-if-you-want-to-sub-for-more-nested-fields-of-already-received-docs-eb3fdbfe4e07) would let us accomplish that.

**Comment by idmontie** [comment]
:+1: Just ran into this problem after spending quite a bit of time trying to debug it. 

I have the following code on in my server folder:

```
Meteor.publish(null, function() {
    return Meteor.users.find({
      _id: this.userId
    }, {
      fields: {
        'services.github.username': 1
      }
    });
  });
```

I can see that this works by running `Meteor.user().services.github.username` in the browser.

When I add this package, the username is no longer available on the browser.

**Comment by benstr** [comment]
solution will be published in the next release.

https://github.com/okgrow/analytics/pull/61

**Comment by idmontie** [comment]
:+1: Awesome!  Any timeframe on that?

**Comment by benstr** [comment]
Soon, this package is getting some much needed lovin this week. But in the meantime feel free to download it and manually add it to your `/packages` folder. Let us know if you find any other issues.

**Comment by pauldowman** [comment]
Version 1.0.1 released.

**Comment by idmontie** [comment]
:+1: :tada:

**Comment by juliomac** [comment]
Thanks! Updating to 1.0.1 also solved for me!
