### ISSUE TITLE
Can't get Google to recognize tracking

### ISSUE THREAD

**Issue by ryanbuiltthat** [okgrow/analytics#63]
I don't know if I missed a step or something but has anyone had any issues with Google taking a while to recognize tracking is installed?

When I run the analytics debugging Chrome extension I see the initialization of `ga` and the creation of a tracker all with the proper ID. I see the events being fired off but my dashboard still shows nothing and says it's not installed.

**Comment by ryanbuiltthat** [comment]
GA picked up tracking ID, just need more patience.

**Comment by ghost** [comment]
I'm having the same issue as you did.

I installed and configured the package about an hour ago. The Chrome extensions reports the "ga" initialization, but still, no views are being shown on the real-time tab of the Analytics reporting dashboard.

How much time did it take for you for the real-time visits count to be shown?

**Comment by ryanbuiltthat** [comment]
Not sure exactly. It was late, I checked it in the morning and everything
was working fine and has been.

**Comment by karldanninger** [comment]
@gatosaurio for me, it can take anywhere from 24 hours to 72 hours. Usually closer to 24 hours. I hope that helps

**Comment by rafa-munoz** [comment]
Now I see it's normal and I need to wait. Thanks.
