### ISSUE TITLE
Exception in onLogin callback: ReferenceError: mixpanel is not defined

### ISSUE THREAD

**Issue by hafizali05** [okgrow/analytics#66]
I am new to meteor stuff as well as analytics so sorry if I dont get some common sense stuff here :)

SO I am trying to create a server side event to track the signup through facebook and google and if done with password than password.

I have installed okgrow package and when I try to track the properties I am unable to track services(fb or google) and roles which are user properties.

Also the major issue I guess is the error which says <b>mixpanel is undefined</b> on the terminal.

This all I am trying to do it on server side in package.js. I have properly set the api.use and files for server to access.

below is the code and the error I am facing.

```
function my_analytics() {
    Accounts.onLogin(function(user){
        if(!user)
            return
        mixpanel.register('user',{
            '$email': user.email[0].address,
            'roles': user.profile.roles
            "services": user.services
        });    
    })
}

Meteor.startup(function(){
    my_analytics();    
})
```

I20151028-19:46:33.319(5.5)? Exception in onLogin callback: ReferenceError: mixpanel is not defined
I20151028-19:46:33.320(5.5)?     at packages/my:package/server.js:18:1
I20151028-19:46:33.320(5.5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20151028-19:46:33.320(5.5)?     at packages/meteor/dynamics_nodejs.js:121:1
I20151028-19:46:33.320(5.5)?     at packages/accounts-base/accounts_server.js:87:1
I20151028-19:46:33.323(5.5)?     at [object Object]._.extend.each (packages/callback-hook/hook.js:102:1)
I20151028-19:46:33.323(5.5)?     at successfulLogin (packages/accounts-base/accounts_server.js:86:1)
I20151028-19:46:33.323(5.5)?     at attemptLogin (packages/accounts-base/accounts_server.js:258:1)
I20151028-19:46:33.323(5.5)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:411:1)
I20151028-19:46:33.324(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20151028-19:46:33.324(5.5)?     at packages/ddp/livedata_server.js:648:1
I20151028-19:46:34.067(5.5)? Exception in onLogin callback: ReferenceError: mixpanel is not defined
I20151028-19:46:34.067(5.5)?     at packages/my:package/server.js:18:1
I20151028-19:46:34.067(5.5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20151028-19:46:34.068(5.5)?     at packages/accounts-base/accounts_server.js:87:1
I20151028-19:46:34.068(5.5)?     at [object Object]._.extend.each (packages/callback-hook/hook.js:102:1)
I20151028-19:46:34.067(5.5)?     at packages/meteor/dynamics_nodejs.js:121:1
I20151028-19:46:34.068(5.5)?     at successfulLogin (packages/accounts-base/accounts_server.js:86:1)
I20151028-19:46:34.068(5.5)?     at attemptLogin (packages/accounts-base/accounts_server.js:258:1)
I20151028-19:46:34.069(5.5)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:411:1)
I20151028-19:46:34.069(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20151028-19:46:34.069(5.5)?     at packages/ddp/livedata_server.js:648:1

**Comment by benstr** [comment]
@hafizali05 this package actually wires all user identification up for you. Just include your mixpanel key in `settings.json` and your app will automatically call the identify function when a user logs in. 

The `mixpanel is undefined` is from you calling `mixpanel.register` in your code. Mixpanel is not available to you, instead we do everything through the `analytics` global. Refer to the analytics.js documentation to see which functions are available to you: https://segment.com/docs/libraries/analytics.js/

**Comment by hafizali05** [comment]
so this would include segment.io to be used right?

anyway around to use mixpanel without segment.io?

**Comment by tsemana** [comment]
@hafizali05 this package doesn't require you to use the segment.io service.  It uses segment.io's analytics.js library to provide a uniform api for all analytics calls.

For you to use your mixpanel service, make sure you configure your mixpanel details in your `settings.json` file (see the Configuration section in the Readme: [Configuration](https://github.com/okgrow/analytics#configuration)):

```
{
  "public": {
    "analyticsSettings": {
      "Mixpanel"         : {"token":  "your-mixpanel-id-here", "people": true},
    }
  }
}
```

Once your app is running, the package will track page views and login/logout/identify events automatically ([Page Views](https://github.com/okgrow/analytics#page-views) & [Log signin/signout](https://github.com/okgrow/analytics#log-signinsignout)), and you can use the `analytics.track()` function to track other events:

```
Template.hello.events({
  'click button': function () {
    // increment the counter when button is clicked
    Session.set('counter', Session.get('counter') + 1);
    analytics.track("Counter incremented", {
      count: Session.get('counter');
    });
  }
});
```

[analytics.track() function details](https://segment.com/docs/libraries/analytics.js/#track)

**Comment by hafizali05** [comment]
one last question and probably I will b done, does analytics.track() work on server side too?

**Comment by benstr** [comment]
@hafizali05 just client side

**Comment by hafizali05** [comment]
@benstr  cant we use analytics-node npm for the server side?

**Comment by pauldowman** [comment]
@hafizali05 I think that's for the Segment service only.
