### ISSUE TITLE
Version constraint - Can't update okgrow:analytics 0.4.3 

### ISSUE THREAD

**Issue by juliomac** [okgrow/analytics#71]
Can't update this package. I get the following message:

```
The following top-level dependencies were not updated to the very latest version available:
 * okgrow:analytics 0.4.3 (1.0.1 is available)
```

I tried the suggested action with `meteor add okgrow:analytics`and got this message:

```
okgrow:analytics without a version constraint has already been added.
```

What could the version constrain be coming from?

I am on Meteor 1.2.1 and have all other packages updated as well.

**Comment by tsemana** [comment]
@juliomac could you clarify: did you remove the current package first with `meteor remove okgrow:anallytics` before trying to run `meteor add okgrow:analytics`?

**Comment by pauldowman** [comment]
Try `meteor update okgrow:analytics`.

**Comment by juliomac** [comment]
Hi @tsemana. Thanks!

No I haven't removed. Now I did and added again. Got 1.0.1 working fine!

Silly I didn't think of it. It should have been the late hours work...

**Comment by tsemana** [comment]
@juliomac glad that fixed it.
