### ISSUE TITLE
ga on server side for webhooks API

### ISSUE THREAD

**Issue by came** [okgrow/analytics#73]
Hi folks,

are there plans (is it possible) to use the package on the meteor server side?
I am having a small  (webhook) API, exposed for mailgun and I want to track some events on ga.
Does this make sense, has anyone tried this?

BR, Carsten

**Comment by benstr** [comment]
@came there are no plans to make this package work server side. Sorry

**Comment by pauldowman** [comment]
@came I added a new issue, #76, for that. The problem is that we use analytics.js which is client-side only, but if anyone wants to discuss it #76 is the place.
