### ISSUE TITLE
Is revenue tracked?

### ISSUE THREAD

**Issue by themeteorchef** [okgrow/analytics#77]
I'm playing with adding the `revenue` property to events along with Mixpanel, however, no revenue data is showing up on Mixpanel. Is this passed along? Note: I'm adding Mixpanel directly through the package and not adding it to Segment. An example event:

```
analytics.track( 'Made a purchase', {
  revenue: 149.00
});
```

The event _does_ show up on Mixpanel, but just as an event for the user. The revenue data shows up in the event data but is not acknowledged by Mixpanel's revenue feature. Any thoughts?

**Comment by themeteorchef** [comment]
I lied. Literally just flipped over and tried again and it showed up. Ignore me :)

**Comment by karldanninger** [comment]
:heart:  :+1:
