### ISSUE TITLE
Facebook "Conversion Tracking" & "Custom Audiences" Integrations

### ISSUE THREAD

**Issue by jorisroling** [okgrow/analytics#79]
How would I configure for the 2 facebook integrations in segment?
I don't know if it is possible, but if it is, what whould be the entry format of the **analyticsSettings** object in **settings.json**.

[analytics.js-integration-facebook-conversion-tracking](https://github.com/segment-integrations/analytics.js-integration-facebook-conversion-tracking)
[analytics.js-integration-facebook-custom-audiences](https://github.com/segment-integrations/analytics.js-integration-facebook-custom-audiences)

**Comment by pauldowman** [comment]
Those aren't supported, and they're not for event tracking so I don't think they should be. I'd like to enhance this package to support adding anything that's supported by segment, but as it is each integration adds a small amount of overhead so I wouldn't add anything but the most popular event tracking services.
