### ISSUE TITLE
Support for oAuth users

### ISSUE THREAD

**Issue by themeteorchef** [okgrow/analytics#8]
I'm working with Mixpanel and trying to identify users in the app. While running the `analytics.debug()` function, I can see the `identify` method being called properly, however, no identity/people data is showing up in Mixpanel (although moving between pages _does_ show up). 

This _appears_ to apply to both `accounts-password` users and `accounts-<service>` users.

Looking at the package code, it looks like there's only support for `accounts-password` users. Specifically this line: 

```
var userEmail = user.emails && user.emails[0] ? user.emails[0].address : 'n/a';
```

Would it be possible to get support for oAuth users added? This would require a little refactor that would look at the `Meteor.user().services.<service>.email` key as well.

I wouldn't be able to do it immediately, but if this is something you'd be open to a PR on, let me know :)

**Comment by tsemana** [comment]
A PR would be welcome for this :)
The original intention was to provide the account-password as example. If you'd like to go ahead and make the update to the package review and merge.

**Comment by pauldowman** [comment]
Yeah it would be great to support that. @themeteorchef if you could even just tell us the names of the variables to look for for each service (and whether they're always set or not) that would help.

**Comment by themeteorchef** [comment]
@pauldowman sure, here's my current hacky solution for this (doesn't cover all cases). With a bit of refactoring this may do the trick.

``` js
/*
* getUserEmail()
* Figure out the user's correct email address. This helps the differing keys
* in the database when using oAuth login.
*/
getUserEmail = function(userId){
  var getUser = Meteor.users.findOne({_id: userId});
  if ( getUser.emails ) {
    return getUser.emails[0].address;
  } else if ( getUser.services ) {
    var services = getUser.services;
    if ( services.facebook ) {
      return services.facebook.email;
    } else if ( services.github ) {
      return services.github.email;
    } else if ( services.google ) {
      return services.google.email;
    } else {
      return null;
    }
  }
}
```

**Comment by pauldowman** [comment]
Awesome @themeteorchef, thanks!

**Comment by alexzaporozhets** [comment]
Hi, this code will not work as expected without adding extra publication (users collection). Also we should consider passing the name not only emails.

http://stackoverflow.com/questions/13151879/publish-certain-information-for-meteor-users-and-more-information-for-meteor-use

**Comment by pauldowman** [comment]
Yeah @tsemana this looks like server-side code.

**Comment by pauldowman** [comment]
To fix it you could publish the service emails (for the current user only), but don't publish the whole services object.

Also no need for a find on the current user.
