### ISSUE TITLE
Add a list of supported services

### ISSUE THREAD

**Issue by AndreasGalster** [okgrow/analytics#81]
It is not clear which services are supported by the package. I'm not 100% sure if htojar for example is supported. The list on atmosphere might suggest this is what is supported but it's not exactly clear. Looking at the package code also doesn't make it very easy to find what is supported unfortuantely.

**Comment by pauldowman** [comment]
The example config in the readme is the actual list. We should update it to make that totally clear. If there's something else you'd like to see supported open an issue and we'll see how many +1's it gets.

**Comment by cfnelson** [comment]
@AndreasGalster Sorry for taking so long to resolve this. The README has been updated with this commit https://github.com/okgrow/analytics/commit/4afa58792e97e1fe3291ec52b00d7871d87f006a

As you already have guessed hotjar isn't currently supported. We are looking into refactoring the way this package works with the intended goal of providing the ability for anyone to add the specific segment.io analytics integration that they need. We will keep you up to date on this progress over on issue #87
