### ISSUE TITLE
How do I turn on Mixpanel integration if I am only using segment.io?

### ISSUE THREAD

**Issue by sferoze** [okgrow/analytics#85]
I am using this package as well as segment.io 

Using segment.io we want the data to go to mixpanel

why do I have to add mixpanel keys in addition to segment keys? 

When I only add the segment keys mixpanel does not get data even though it is turned on inside segment. 

But I should only have to add segment keys. 

Once I add segment keys is there a way I can use segment to send data to mixpanel?

**Comment by sferoze** [comment]
Basically in the identify call

```
analytics.identify('019mr8mf4r', {
  email: 'achilles@segment.com',
  plan: 'Premium'
}, {
  integrations: {
    'All': false,
    'Mixpanel': true,
    'KISSmetrics': true
  }
});
```

can we set the integrations? is the default all true?

**Comment by pauldowman** [comment]
If you have a segment account I think you should be able to just configure this package to use segment, you don't need to configure it with your Mixpanel and KISSmetrics keys. Like so:

```
{
  "public": {
    "analyticsSettings": {
      "Segment.io"       : {"apiKey": "..."}
    }
  }
}
```

Then in segment you can set up the mixpanel integration. I think that's all you need to do. This means the only client-side integration is segment, and server-side (in segment) you can send the data on to Mixpanel and KISSmetrics.

Let me know if that doesn't solve it.

**Comment by sferoze** [comment]
@pauldowman Unfortunately this does not work. At first I only added segment. But the info was not sent over to Mixpanel even though mixpanel was turned on I had set the API keys correctly in segment. 

Could it be related to this: https://segment.com/docs/libraries/analytics.js/#selecting-integrations

I think you need to set integration key to all in the identify call. Otherwise segment gets the data but does not send the data to any integrations.
