### ISSUE TITLE
Amplitude not working

### ISSUE THREAD

**Issue by d4nyll** [okgrow/analytics#88]
When I tried to add my Amplitude API key, it comes back with the error:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

My API key is correct, and I have **_not**_ added it as an integration on Segment.io

My `settings.json` looks like this:

```
{
  "public": {
    "analyticsSettings": {
      "Amplitude"        : {"apikey": "88c08e5ae5d54a8df5c947b2c2d84d73"},
      "Segment.io"       : {"apiKey": "PBmof0WnR67uNoiM39f6E0kPvXszeS63"}
    }
  }
}
```

**Comment by molinto** [comment]
I get the same error too, trying to follow this tut:
https://themeteorchef.com/blog/tracking-user-behavior/

**Comment by pauldowman** [comment]
It looks like the key in the settings object should be 'apiKey' (note the capitalization). See [here](https://github.com/okgrow/analytics.js/blob/okgrow-supported-integrations/analytics.js#L7246). Try that and I'll update the README.

**Comment by molinto** [comment]
Seems to work for me. Thanks Paul :)
