### ISSUE TITLE
Disabling auto page view logging

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#89]
Hi,

I'm putting this out here as a feature request. I may implement this myself at some point and make a pull request. Let me know if a pull request offering the following would be accepted:

I'd like to have finer control over page view logging. There are redirect pages I use that are currently being logged as page views. Also, sometimes the url changes, but it's not really a change of page - the main page template is still the same and I don't necessarily want to count that as a page view. So I'd like there to be an option to turn off auto page logging.

I also want to be able to disable auto mixpanel logging for all pages. I want to use mixpanel for specific events that I set up so that I stay within the free tier limit. Logging all page views means I exceed the limit within days.

**Comment by pauldowman** [comment]
We've heard this a few times. I think we would consider a PR if it didn't add much complexity overall and didn't affect usage in the normal case.

**Comment by danielsvane** [comment]
I made a pull request which fixes this issue: #96

**Comment by abdelrahman-elkady** [comment]
+1 here, don't need to track everything and exceed my mixpanel plan as a student doing my research, would be great if merged soon

**Comment by elie222** [comment]
Abdel, you can use the pull request already. Create a packages folder in
your app and then git clone the git repo containing the pull request to it.
If you then run meteor list in the command line, you should see that okgrow
analytics has a plus sign next to it and is a local package.

**Comment by abdelrahman-elkady** [comment]
:+1: yes that would be great, thanks a lot

**Comment by benstr** [comment]
PR #96 has been merged, closing this issue.
