### ISSUE TITLE
Move analyticsSettings outside of public

### ISSUE THREAD

**Issue by kevohagan** [okgrow/analytics#9]
Meteor.settings is available on the client, is there a specific reason to keep analyticsSettings in public?

**Comment by pauldowman** [comment]
I don't think that's correct. Only Meteor.settings.public is available on the client. http://docs.meteor.com/#/full/meteor_settings

**Comment by kevohagan** [comment]
sorry i meant Meteor.settings.public! 
I mean, right now, anyone can just open their browser console and get your API keys for all services! Isn't that maybe not best practice? 
Just wondering if it wouldnt be better to check server side for the  analyticsSettings and then initiate analytics.js on the client?
Or am i missing something here

**Comment by kevohagan** [comment]
is that an issue @pauldowman ?

**Comment by pauldowman** [comment]
The configuration for those services are meant to be on the client side, it's not an issue. They're not sensitive. You can look at any web page that uses Google Analytics or Mixpanel and see the tracking code.
