### ISSUE TITLE
Please change Keys to lowercase & dash-separated

### ISSUE THREAD

**Issue by kidsil** [okgrow/analytics#91]
When Meteor is bundled, settings keys have their spaces removed. This means Google Analytics will become GoogleAnalytics (and thus won't work).

This can be easily avoided by having the keys look like keys, i.e. lowercase & dash-separated

**Comment by pauldowman** [comment]
@kidsil I haven't seen that. Can you give me steps to reproduce it?

**Comment by kidsil** [comment]
Simply add Google Analytics to the settings. json file, bundle your Meteor
application (the bug doesn't appear on "meteor run", only when the
application is deployed).
The issue is that when the public settings get minified, the spaces are
getting dropped.

I'm running the bundled application behind nginx (just in case that helps).

**Comment by pauldowman** [comment]
@kidsil I'm sorry but I really don't understand. By "bundle" I'm assuming you mean `meteor build`, and I'm pretty sure that the built meteor app wouldn't include the settings.json file. It shouldn't anyway, your settings are for runtime configuration.

I'm going to close this for now, but please do explain and we can reopen if I can understand the scenario.
