### ISSUE TITLE
Absolute positioned link elements' event triggers break on iOS

### ISSUE THREAD

**Issue by PeterChauYEG** [okgrow/analytics#93]
I encountered a bug which occurs when this package is installed (using `meteor add okgrow:analytics`). It seems that upon installation, my link elements' event triggers stop working on mobile (iOS Chrome and Safari). I believe it only affects elements which are absolute positioned (`position: absolute;`). 

There is no apparent change on a desktop browser.

I'll let you know if I can figure it out. Perhaps it's a dependency thing.
## Packages before installing okgrow:analytics:

blaze-html-templates         1.0.1
check                        1.1.0 
ecmascript                   0.1.6*
email                        1.0.8
es5-shim                     4.1.14
fortawesome:fontawesome      4.5.0 
fourseven:scss               3.4.1 
jquery                       1.11.4 
kadira:flow-router-ssr       3.8.0\* 
kadira:react-layout          1.5.3 
meteor-base                  1.0.1 
meteorhacks:kadira           2.27.2\* 
mobile-experience            1.0.1
mongo                        1.1.3
react                        0.14.3*
seba:minifiers-autoprefixer  0.0.1
session                      1.1.1
themeteorchef:bert           2.1.0 
tracker                      1.0.9
twbs:bootstrap               3.3.6

[Github of a repository which you can replicate the bug with](https://github.com/PeterChauYEG/bug)

Run with `npm run-scripts start-development`

**Comment by pauldowman** [comment]
Thanks @PeterChauYEG and @RobertLowe, we'll check this out ASAP.
