### ISSUE TITLE
Question: How to display tracked data in web app?

### ISSUE THREAD

**Issue by sylverfyst** [okgrow/analytics#95]
Is there a better way to do this than storing the data in an array like the emitter example?  I'm trying to implement a dashboard feature where users can track how much attention their listing is retrieving and the tracking is great, I'd just like to be able to send that info back to the web app

**Comment by rfines** [comment]
+1 I would be really interested to know the answer to this as well. I imagine it will be a separate integration with the Google Analytics API since this package seems to only include and initialize the scripts to do the tracking and stuff and does not seem to have any of the actual API's integrated.

**Comment by sylverfyst** [comment]
I did find a little bit of a work around, in that I wrote a custom callback on page calls, to store tracking data in the app, but what I would really like is for there to be a request that returns the data from the tracking service in a readable format.  I'm working in meteor, so mine looked a little like this:  
`analytics.page('listing', listingId, {
        title: listing.title,
        id: listing._id,
    }, {}, Meteor.call("serverMethod_incrementListingField", listing, "viewCount", viewCount, function (error, result) {      
            if (error) { console.log(error); };
        })
    );`

**Comment by pauldowman** [comment]
I think this is outside of the scope of this package. Some analytics services let you query the data that you put in, I think that's the way I would do this.
