### ISSUE TITLE
Intercom 403 Errors

### ISSUE THREAD

**Issue by charleshan** [okgrow/analytics#97]
`https://api-ping.intercom.io/vjs/users/ping Failed to load resource: the server responded with a status of 403 (Forbidden)`
`https://api-iam.intercom.io/vjs/users/events Failed to load resource: the server responded with a status of 403 (Forbidden)`

**Comment by charleshan** [comment]
It seems to be related to this: https://segment.com/docs/integrations/intercom/#secure-mode
Does this package not have this integrated?

**Comment by karldanninger** [comment]
Hey @OminStyle, our analytics.js port may be out of date. I'll label this and take a look at this as soon as we can!

**Comment by kartikTT** [comment]
Any update on this? Seeing the same issue

**Comment by pablolarvor** [comment]
Hey ! Any update ? Same for me

**Comment by pablolarvor** [comment]
You can fix it with this: 

Client:

``` js
Meteor.startup(function() {
  var hashSub = Meteor.subscribe('currentUserIntercomHash');

  Tracker.autorun(function() {
    if (hashSub.ready() && Meteor.user()) {
      analytics.identify(Meteor.user()._id, {
        email: Meteor.user().emails[0].address,
        createdAt: Meteor.user().createdAt
      }, {
        Intercom: {
          user_hash: Meteor.user().intercomHash
        }
      });
    }
  });
});
```

Server : 

``` js
import crypto from 'crypto';

// returns undefined if there is no secret
IntercomHash = function(userId) {
  var secret = Meteor.settings &&
      Meteor.settings.private.intercom && Meteor.settings.private.intercom.secret;

  if (secret) {
    return crypto.createHmac('sha256', new Buffer(secret, 'utf8'))
      .update(userId).digest('hex');
  }
};

Meteor.publish('currentUserIntercomHash', function() {
  if (this.userId) {
    var intercomHash = IntercomHash(this.userId);
    if (intercomHash) {
      this.added("users", this.userId, {intercomHash: intercomHash});
    }
  }
  this.ready();
});
```

**Comment by markshust** [comment]
How can we contribute to this repo? The file `vendor/analytics.min.js` is minified. I'd like to fix this issue.

**Comment by cfnelson** [comment]
@markoshust we are grabbing the minified file from our fork of segment.io's analytics.js, which can be found [here](https://github.com/okgrow/analytics.js). We need to update that repo and do a rebuild to generate the minified file. Hopefully we can get to it next week.

**Comment by arrygoo** [comment]
@pablolarvor @IamCharlesHan @kartikTT  Does the new release fix your intercom issue? We are now using the latest Segment.io build.

**Comment by ACPK** [comment]
@cfnelson  - Any fix for this?

**Comment by cfnelson** [comment]
@ACPK Are you still having this issue with the latest version of this package? Please re-open if you are, it should have been resolved when the segment min file was updated.
