### ISSUE TITLE
Use https endpoints instead of http

### ISSUE THREAD

**Issue by charlottetan** [okgrow/analytics#99]
Several external scrips are loaded via http instead of https and this could compromise production apps, as well as cause browsers to display warnings about pages being insecure

**Comment by cfnelson** [comment]
@charlottetan As far as I understand the request you have made is outside the scope of this package. This package is only wrapping segment.io's analytics.js and adding functionality for easy analytics tracking with IronRouter or FlowRouter. Using ssl is dependent on if the analytics service supports/provides ssl.

If you are using the [BrowserPolicy Package](https://atmospherejs.com/meteor/browser-policy) you can modify your `BrowserPolicy.content` to only allow https, see this package's readme for [example](https://github.com/okgrow/analytics#browser-policy). If I have misunderstood what you are asking here please let me know and I will try my best to help.
